In [ ]:
pip install -q yahoo_fin > /dev/null

In [2]:
pip install --upgrade yfinance > /dev/null

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyppeteer 2.0.0 requires websockets<11.0,>=10.0, but you have websockets 16.0 which is incompatible.
google-adk 1.29.0 requires websockets<16.0.0,>=15.0.1, but you have websockets 16.0 which is incompatible.
gradio-client 1.14.0 requires websockets<16.0,>=13.0, but you have websockets 16.0 which is incompatible.

In [3]:
mkdir -p data results log

In [4]:
from google.colab import drive
drive.mount('/content/drive')
# ! find /content/drive/MyDrive/colab/ -type f -mtime +180 -delete -print

Mounted at /content/drive

In [5]:
import numpy as np
import pandas as pd

In [6]:
def show_prediction(name, suffix):
  df = pd.read_csv(f'results/{name}_{suffix}_predictions.csv')
  df['predicted_return'] = ((df['predicted_max']+df['predicted_min']+df['predicted_close'])/3 - df['current_price'])/df['current_price']
  return df.sort_values('predicted_return', ascending=False, key=abs)

In [7]:
def run_command_with_check(command):
  """Runs a command, prints stderr, and raises an exception if it fails."""
  process = subprocess.run(command, shell=True, capture_output=True, text=True, check=False)

  if process.returncode != 0:
    print("stderr:", process.stderr)  # Print stderr only on error
    raise subprocess.CalledProcessError(process.returncode, process.args, output=process.stdout, stderr=process.stderr)
  else:
    # Print or process stdout if needed
    #print("stdout:", process.stdout)
    pass

  return process.returncode

In [8]:
import os
import subprocess
def run_model_nn_cmd(prefix, version, do_train=False, window_size=None, future_days=None, hourly=False, copy_tickers=True):
    # copy drive/MyDrive/colab/results/nnreturn.py to local folder
    tickers = f"{prefix}tickers.csv"
    run_command_with_check(f"cp  /content/drive/MyDrive/colab/nnreturn.py .")
    if copy_tickers:
      run_command_with_check(f"cp  /content/drive/MyDrive/colab/tickers/{tickers} .")
    if not do_train:
      run_command_with_check(f"cp  /content/drive/MyDrive/colab/models/{prefix}_{version}_*.pth .")
      # Run nnreturn.py in results folder and throw exception if error
      today = pd.to_datetime('today').strftime('%m%d')
      run_command_with_check(f"rename 's/{version}/{today}/' *.pth")
      cmd_arg = ""
      if window_size:
        cmd_arg += f" --window-size {window_size}"
      if future_days:
        cmd_arg += f" --future-days {future_days}"
      if hourly:
        cmd_arg += " --hourly"
      run_command_with_check(f"python3 nnreturn.py --tickers-file {prefix}tickers.csv --mode analyze {cmd_arg}")
      run_command_with_check(f"cp {prefix}*predictions.csv results")
      # Get today's date

      return show_prediction(prefix, today)
    else:
      raise Exception("Not implemented")

In [ ]:
run_model_nn_cmd('etf', '0730').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
47,XLRE,41.43,2026-04-02,2026-04-30,36.52,42.07,36.99,-0.070078
34,VNQ,89.72,2026-04-02,2026-04-30,80.22,91.08,82.28,-0.057884
53,XOP,177.25,2026-04-02,2026-04-30,158.57,179.76,164.20,-0.054951
29,SMOG,138.66,2026-04-02,2026-04-30,126.34,140.72,130.10,-0.045243
14,IPO,42.12,2026-04-02,2026-04-30,42.03,44.21,45.03,0.038857
7,DXYZ,28.23,2026-04-02,2026-04-30,27.18,31.14,29.60,0.038139
46,XLP,81.65,2026-04-02,2026-04-30,74.71,82.62,78.84,-0.035844
54,XSW,143.99,2026-04-02,2026-04-30,129.66,148.52,140.56,-0.030627
4,DAPP,14.86,2026-04-02,2026-04-30,14.22,15.65,13.37,-0.030058
21,JETS,24.80,2026-04-02,2026-04-30,23.19,25.34,23.67,-0.029570

In [ ]:
# 0716 is hourly 20
run_model_nn('idx', '0716', window_size=20, future_days=8, hourly=True).head(10)

In [ ]:
import runml.pipeline
from runml import pipeline,findata
#from importlib import reload
# reload(runml.pipeline)

In [ ]:
# Skip some days from consecutive window to lessen test /train overlap
# findata.G_NON_OVERLAP= 0

Run following if like to save results in drive

In [ ]:
import numpy as np
# profit factor 2 = 50% of predicted gain due to early profit taking
def addAlloc(df, stop_loss, profit_factor=2):
  df['Alloc'] = df['Accu']/stop_loss - (1-df['Accu'])*profit_factor/abs(df['Gain'])
  df['Alloc'] = np.where(df['Alloc'] < 0, 0, df['Alloc'])
  return df

# profit factor 2 = 50% of predicted gain due to early profit taking
def addAllocHL(df, stop_loss, profit_factor=1):
    # Simplify following using apply
    def calculate_alloc(row):
        gain_low = min(row['Gain_l'], 0)
        gain_high = max(row['Gain_h'], 0)
        gain = min(row['Gain'], gain_high)
        average_gain = (gain_low+gain_high + 2*gain)/4
        if (average_gain == 0):
          return 0
        avg_accuracy = (row['Accu']+row['Accu_l']+row['Accu_h'])/3
        alloc =  avg_accuracy/stop_loss - (1-avg_accuracy)*profit_factor/abs(average_gain)
        return round(max(alloc, 0), 2)
    df['Alloc'] = df.apply(calculate_alloc, axis=1)
    return df

pd.options.display.max_columns = None

In [ ]:
import os
# findata.EPOCHS=200
def run_model(prefix, version, tickers, do_train):
  if (not do_train):
    os.system(f"cp  /content/drive/MyDrive/colab/results/{prefix}-{version}-* ./results/")
  mod = pipeline.RateReturnOnly(
    pipeline.FeatureSeq([pipeline.AddDayMonth(), pipeline.AddVWap(),
                         pipeline.AddMA(200), pipeline.Adj()]))
  df= pipeline.runModelCombinedVola(tickers, f"{prefix}-{version}", mod, do_train)
  # Save datafrme to prefix-version-prediction.csv
  df.to_csv(f"results/{prefix}-{version}-prediction.csv")
  return df

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
findata.G_SCALER = 'minmax' # Change to minmax
tickers = ['ABNB', 'ACLS' ,'AI', 'AMBA', 'APP',
           'BASE', 'BILL', 'BMBL', 'BYRN', 'CELH', 'CFLT', 'COHR', 'CRWD', 'CVNA',
           'DASH', 'DBX', 'DDOG', 'DOCN', 'DOCS', 'DOCU', 'DT', 'DXCM',
           'ELF', 'ENPH', 'ESTC', 'ETSY', 'EXPE', 'FIVE', 'FOUR',
           'GFS', 'GTLB', 'GLBE', 'HCP', 'HIMS', 'HOOD', 'HUBS',
           'INMD', 'INTA', 'IOT', 'IRDM', 'JAKK', 'JKS', 'KD', 'LYFT',
           'MBLY', 'MDB',  'MNDY', 'MNST', 'MPWR', 'MRVL', 'MXL','MTCH', 'MU',
           'NET', 'NVCR', 'NTNX', 'OKTA', 'OLED',
           'PAR', 'PANW',  'PAYX', 'PD', 'PI', 'PINS',
           'RBLX', 'RKLB', 'RMBS', 'RUM', 'SMCI', 'SMAR', 'SNAP', 'SNOW', 'SQ', 'SPOT',
           'SOUN', 'TEM', 'TEAM', 'TDOC', 'TMDX', 'TNDM', 'TOST', 'TRIP', 'TTD', 'TWLO',
           'U','UI', 'UBER', 'UPWK', 'WOLF', 'VEEV', 'Z', 'ZM', 'ZS']
df = run_model('ipos', '2a', tickers, True)

In [ ]:
addAllocHL(df, 0.10, 1)
df[(df.Gain>0)].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.EPOCHS=200
findata.G_SCALER = 'standard'
# https://seekingalpha.com/etfs-and-funds/etf-tables/sectors
tickers1 = ['ARKF', 'ARKK', 'ARKW', 'CIBR', 'DAPP', 'DIA', 'DTEC', 'DXYZ',
            'EEM', 'FDN', 'FPX',
            'ICLN', 'IGV', 'IJK', 'IJR', 'IPO',
            'IXC', 'IXN', 'IXP', 'IWM', 'IWO', 'IYZ',
            'JETS', 'JXI', 'MGK', 'MGV', 'MTUM',
            'ONLN', 'QQQ', 'SMH', 'SMOG', 'SPY', 'TDIV',
            'URA', 'VNQ', 'VT', 'VTI', 'VUG', 'WDIV', 'XITK',
            'XLB', 'XLC', 'XLE', 'XLF', 'XLI', 'XLK', 'XLP',
            'XLRE', 'XLU', 'XLV', 'XLY', 'XME', 'XNTK', 'XSW' ]
df1 = run_model('etf', '1b', tickers1, True)

In [ ]:
detail = res['ARKK'].final_df

mindate = detail['date'].min()
totalday = (detail['date'].max()-mindate).days
detail['diff'] = ((detail['date']-mindate).dt.days+1)/totalday
detail['sum_profit'] = (detail['buy_profit'] + detail['sell_profit'])/detail['adjclose']
detail['predicted_profit'] = ((detail['adjclose_15']-detail['adjclose'])/detail['adjclose']).abs()
profit_df = detail[detail['sum_profit'] > 0][['sum_profit', 'predicted_profit']]
average_profit = (profit_df['sum_profit']).mean()
excess_profit = (profit_df['sum_profit'] - profit_df['predicted_profit']).mean()
average_loss = -detail[detail['sum_profit'] < 0]['sum_profit'].mean()
detail['has_profit'] = np.where(detail['sum_profit'] > 0, 1 , 0)

accuracy = detail['has_profit'].mean()
weight_accuracy = (detail['has_profit']*detail['diff']).sum()/detail['diff'].sum()
(accuracy, weight_accuracy, average_profit, excess_profit, average_loss)

In [ ]:
addAlloc(df1, 0.10, 1)
df1.sort_values('Alloc', ascending=False)

In [ ]:
df1.to_csv('results/etf_12b_predictions.csv')

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
findata.G_SCALER = 'minmax'
tickers3 = [ 'AIRI', 'ALSMY', 'AMSC', 'AMSSY', 'ACHR',
            'APPS',  'AUR',  'ATOM', 'AWRE', 'AXTI',
            'BKKT', 'BGSF', 'BLDE', 'BLNK',
            'CARS', 'CHGG', 'CLOV', 'CRCT', 'CXM',
            'DLO', 'DM', 'EVGO', 'FSLY',
            'GOGO', 'GRAB', 'GRPN', 'GTE', 'HIMX', 'HIVE',
            'INDI', 'INLX',  'INVZ', 'JOBY',  'KIND',
            'LAZR', 'LFMD', 'LUMN', 'MAX', 'MITK', 'MTTR', 'MYTE',
            'NEPH', 'NNOX', 'OMQS', 'ONDS', 'OPEN', 'OTLY', 'OUST',
            'PAYO', 'PGY', 'PLUG', 'PTON', 'PUBM',
            'REAL', 'REI', 'RIG', 'RVYL',
            'SABR', 'SFIX', 'SLDP', 'SLE', 'SMWB', 'SST', 'STEM',
            'TDW', 'TDOC', 'TRUP', 'VTEX', 'VSAT', 'YEXT']
df3 = run_model('vols', '12b', tickers3, False)

In [ ]:
# df3.sort_values('Gain', ascending=False)
addAlloc(df3, 0.17, 1)
df3[(df3.Gain>0)].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.EPOCHS=200
tickers4 = ['AAPL', 'ACN', 'ADBE', 'AMD', 'AMZN', 'AVGO', 'BA', 'BKNG', 'BRK-B',
            'CAT', 'CDNS', 'CRM', 'COST', 'CSCO', 'DE', 'DELL', 'DHR', 'DIS',
            'GOOGL', 'FDX', 'HD', 'INTC', 'IBM', 'ISRG', 'KO', 'LLY',
            'META', 'MMC', 'MSFT', 'NKE', 'NVDA', 'NOW',
            'ORCL', 'PYPL', 'QCOM', 'SBUX',
            'TMO', 'TSLA', 'TXN', 'UNH', 'UPS', 'WMT']
df4 = run_model('mcap', '1b', tickers4, True)

In [ ]:
# df4.sort_values('Gain', ascending=False)
addAlloc(df4, 0.14, 1)
df4.sort_values('Alloc', ascending=False)

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
tickers5 = ['ASML', 'ADDDF', 'ADYEY',
            'BAK', 'BASFY', 'BESIY',
            'CAAP', 'CDUAF', 'COTY', 'COVTY', 'CDMGF', 'CX', 'DBOEY', 'DNNGY',
            'EADSF', 'EIFZF', 'EDNMF', 'ENGGY',
            'EQNR', 'ERIC', 'ERJ','ESEA', 'EVKIY',
            'FANUY', 'FDRVF', 'FQVLF', 'GLCNF',  'GLOB', 'HCMLY', 'HDELY',
            'HENKY', 'HYMTF', 'HMC', 'KNNGF', 'MELI', 'MGA',
            'RACE', 'LIN', 'LYB', 'LVMUY',
            'NHYDY', 'NOK', 'NU', 'NVO', 'NXPI',
            'ONON', 'OTGLY', 'PAX', 'POAHF', 'PROSF',
            'RNMBF', 'RYCEF', 'SAFRF', 'SFTBY',
            'SAP', 'SE', 'SIEGY', 'STLA',
            'TEF', 'TELNF', 'TGLS','THQQF', 'TKAMY', 'TRYIY', 'TSM',
            'VALE', 'VNT', 'YARIY', 'ZURVY']

df5 = run_model('gstock', '2a', tickers5, False)

In [ ]:
addAllocHL(df5, 0.14)
df5[df5.Gain > 0].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.G_SCALER = 'standard'
tickers6 = ['ARGT', 'EWD', 'FLN',
           'ECH', 'EPHE', 'EWA', 'EWG', 'EWI', 'EWJ',
           'EWC', 'EWM', 'EWP', 'EWT', 'EWW', 'EWY', 'EWZ',
           'IDX', 'ILF', 'INDA', 'KEMQ', 'KWT', 'THD', 'TUR', 'VNM', 'XCEM']
df6 = run_model('etf', '12a', tickers6, False)

In [ ]:
addAllocHL(df6, 0.07, 1)
df6.sort_values('Alloc', ascending=False)

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
findata.G_SCALER = 'standard'
tickers7 = ['AAL', 'ADI', 'ALB', 'AMR','ANF', 'APO', 'AQN', 'ARCH', 'ARE', 'ASC',
            'BAH', 'BAX', 'BKR', 'BLK', 'BX', 'BXC',
            'CBT', 'CC', 'CCI', 'CCJ', 'CF', 'CI', 'CIVI', 'CTAS',
            'CG',  'CLS', 'CMI', 'COKE', 'COP', 'CSL',
            'DAL', 'DD', 'DINO', 'DVN', 'DXC', 'EMN',
            'F', 'FCX', 'FICO', 'FIS', 'FLO', 'FMS', 'FSLR', 'GLW', 'GWW',
            'HIW', 'HSII', 'HPE', 'IFF', 'IP', 'IPI', 'IVZ',
            'KD', 'KHC', 'KMB', 'KVUE',
            'MMM', 'MOD', 'MPC', 'NFG', 'NTR', 'OMC', 'OLN', 'OSK',
            'PARA', 'PCAR', 'PEP', 'PETS', 'PNR', 'POR', 'POWL', 'PSTL',
            'RCL', 'RH', 'ROP',
            'SAFE', 'SBLK', 'SCCO', 'SPTN', 'SPG', 'SRE', 'STLD', 'STRL', 'SWK',
            'T', 'TEX', 'TGT', 'TDG', 'TMUS','TWI', 'UAL', 'URI',
            'VRTX', 'VZ', 'WDC', 'WHR', 'WSM', 'XOM', 'YORW', 'ZTS']
df7 = run_model('val', '1a', tickers7, False)

In [ ]:
dfp = run_model_nn_cmd('pennystock', '1226')

In [ ]:
dfp[dfp['predicted_return'] > 0].head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
70,FUBO,13.82,2026-05-01,2026-05-29,12.95,20.66,18.48,0.256392
92,BYND,0.95,2026-05-01,2026-05-29,0.83,1.33,1.17,0.168421
4,APPS,3.68,2026-05-01,2026-05-29,3.52,4.93,4.30,0.154891
97,SQNS,3.47,2026-05-01,2026-05-29,3.27,4.59,4.07,0.146013
79,GTM,6.65,2026-05-01,2026-05-29,6.09,9.28,7.47,0.144862
54,SLE,3.93,2026-05-01,2026-05-29,3.34,5.75,4.28,0.134012
31,LFMD,5.00,2026-05-01,2026-05-29,4.67,6.51,5.82,0.133333
90,SBET,7.29,2026-05-01,2026-05-29,6.67,10.57,7.38,0.125743
7,AWRE,1.14,2026-05-01,2026-05-29,1.04,1.72,1.09,0.125731
93,NXDR,1.65,2026-05-01,2026-05-29,1.65,2.08,1.83,0.123232

In [ ]:
addAllocHL(df7, 0.10, 1)
df7[df7.Gain > 0].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.EPOCHS=200
tickers8 = [ 'DBC', 'FXB', 'FXE', 'FXF', 'FXY',
            'GLD', 'ISHG', 'PDBC', 'SLV', 'SOYB',
            'TIP', 'TLT', 'USO', 'UUP', 'VTIP', 'WEAT']

df8 =  run_model('com', '12a', tickers8, True)

In [ ]:
addAllocHL(df8, 0.10, 1)
df8.sort_values('Alloc', ascending=False)

In [ ]:
run_model_nn_cmd('bluechipstock', '0221').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
41,UPS,95.79,2026-05-19,2027-05-04,93.63,162.64,153.63,0.426384
33,ORCL,182.38,2026-05-19,2027-05-04,173.16,326.76,266.91,0.401524
37,TMO,450.78,2026-05-19,2027-05-04,434.90,749.91,707.13,0.399012
6,AVGO,409.30,2026-05-19,2027-05-04,345.09,672.68,641.34,0.351177
38,TSLA,396.22,2026-05-19,2027-05-04,349.70,680.84,518.36,0.303064
23,INTC,104.29,2026-05-19,2027-05-04,86.40,171.06,148.74,0.298303
30,NKE,43.06,2026-05-19,2027-05-04,41.07,64.20,62.12,0.295789
18,DIS,103.21,2026-05-19,2027-05-04,98.35,151.93,137.89,0.253658
20,GOOGL,389.02,2026-05-19,2027-05-04,366.51,531.49,521.70,0.216476
14,CSCO,115.62,2026-05-19,2027-05-04,110.97,156.17,153.41,0.212449

In [ ]:
findata.EPOCHS=200
findata.G_SCALER = 'standard'
tickers9 = [ 'ADA-USD', 'AVAX-USD', 'BTC-USD', 'BCH-USD', 'DOGE-USD', 'DOT-USD',
            'ETH-USD', 'FIL-USD', 'ICP-USD', 'LINK-USD', 'LTC-USD',
            'MATIC-USD', 'NEAR-USD', 'SOL-USD', 'TON-USD', 'TRX-USD', 'XRP-USD']
df9 = run_model('cry', '11b', tickers9, False)

In [ ]:
addAllocHL(df9, 0.14, 1)
df9.sort_values('Alloc', ascending=False)

In [ ]:
run_model_nn_cmd('country', '1112').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
18,INDA,49.78,2026-05-07,2026-06-04,47.52,57.07,53.45,0.058256
20,KWT,38.68,2026-05-07,2026-06-04,37.33,41.90,41.90,0.043864
5,EWA,29.50,2026-05-07,2026-06-04,27.07,30.01,28.37,-0.034463
16,IDX,13.18,2026-05-07,2026-06-04,12.98,14.00,13.85,0.032625
9,EWC,57.88,2026-05-07,2026-06-04,52.79,60.19,55.67,-0.028738
15,EWZ,38.79,2026-05-07,2026-06-04,36.47,39.44,37.71,-0.023632
12,EWT,94.30,2026-05-07,2026-06-04,87.13,95.57,93.81,-0.022587
14,EWY,176.73,2026-05-07,2026-06-04,165.62,180.06,173.07,-0.021577
8,EWJ,91.00,2026-05-07,2026-06-04,86.58,92.32,88.50,-0.020513
23,VNM,19.53,2026-05-07,2026-06-04,19.07,20.67,19.97,0.019116

In [ ]:
run_model_nn_cmd('global', '1107').head(15)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
0,ADDDF,173.00,2026-05-05,2026-06-02,170.79,210.49,194.08,0.108593
67,NVTS,17.55,2026-05-05,2026-06-02,16.03,21.96,20.11,0.103514
63,NJDCY,3.81,2026-05-05,2026-06-02,3.27,4.84,4.48,0.101487
4,APTV,54.83,2026-05-05,2026-06-02,53.97,65.15,58.36,0.078971
59,MELI,1817.31,2026-05-05,2026-06-02,1780.60,2108.69,1977.69,0.076129
82,SAFRF,321.16,2026-05-05,2026-06-02,313.15,352.46,367.54,0.072311
16,CDMGF,22.75,2026-05-05,2026-06-02,19.04,22.98,21.38,-0.071062
52,KEP,15.54,2026-05-05,2026-06-02,14.75,18.24,16.69,0.065637
48,HMC,24.16,2026-05-05,2026-06-02,23.12,27.40,26.41,0.061396
26,DOLE,14.80,2026-05-05,2026-06-02,12.78,15.14,13.84,-0.059459
40,FCX,57.68,2026-05-05,2026-06-02,57.32,64.77,60.63,0.055941
18,COTY,2.56,2026-05-05,2026-06-02,2.41,2.94,2.73,0.052083
78,RIG,6.25,2026-05-05,2026-06-02,5.34,6.43,6.01,-0.051733
98,TKAMY,12.22,2026-05-05,2026-06-02,11.54,13.40,13.54,0.049645
66,NVO,44.87,2026-05-05,2026-06-02,42.60,50.11,48.51,0.049105

In [ ]:
run_model_nn_cmd('valuestock', '0301').head(15)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
68,KD,13.46,2026-04-28,2026-05-26,13.17,17.41,14.65,0.120109
127,VST,161.12,2026-04-28,2026-05-26,158.90,191.87,186.47,0.111470
121,TWI,8.13,2026-04-28,2026-05-26,8.18,9.70,8.96,0.100451
9,ARE,40.41,2026-04-28,2026-05-26,40.13,47.03,46.10,0.099233
35,CVS,80.98,2026-04-28,2026-05-26,66.12,83.11,70.63,-0.095003
115,TDG,1154.06,2026-04-28,2026-05-26,1142.60,1328.15,1309.62,0.091905
15,BLK,1049.76,2026-04-28,2026-05-26,1020.87,1206.37,1206.85,0.090437
122,UAL,90.41,2026-04-28,2026-05-26,89.65,107.96,97.75,0.088965
93,PNR,82.86,2026-04-28,2026-05-26,81.64,96.05,92.93,0.088664
74,M,19.43,2026-04-28,2026-05-26,19.11,21.16,23.09,0.086979
66,IPI,37.53,2026-04-28,2026-05-26,31.66,37.02,34.57,-0.082956
69,KHC,22.47,2026-04-28,2026-05-26,22.43,24.73,25.74,0.081442
26,CG,47.72,2026-04-28,2026-05-26,47.63,55.48,51.40,0.079282
0,AAL,11.64,2026-04-28,2026-05-26,11.74,14.07,11.86,0.078751
77,MMM,146.03,2026-04-28,2026-05-26,147.99,173.44,150.44,0.077107

In [9]:
run_model_nn_cmd('commodity', '0312').head(5)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
4,FXY,57.75,2026-05-21,2026-06-18,56.41,60.08,58.68,0.011082
6,ISHG,75.37,2026-05-21,2026-06-18,73.36,77.90,76.69,0.008138
2,FXE,107.27,2026-05-21,2026-06-18,104.63,110.68,108.30,0.005593
1,FXB,129.23,2026-05-21,2026-06-18,125.94,133.46,130.18,0.004875
9,SOYB,25.01,2026-05-21,2026-06-18,24.35,25.63,24.83,-0.002932

In [10]:
run_model_nn_cmd('crypto', '0214').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
16,AAVE-USD,89.23,2026-05-21,2026-06-18,88.99,109.27,103.02,0.125481
1,ETH-USD,2138.12,2026-05-21,2026-06-18,2097.58,2738.65,2247.69,0.104385
18,ATOM-USD,2.04,2026-05-21,2026-06-18,2.01,2.58,2.07,0.088235
4,XRP-USD,1.38,2026-05-21,2026-06-18,1.37,1.60,1.53,0.086957
0,BTC-USD,77689.45,2026-05-21,2026-06-18,77684.35,91403.61,82915.85,0.081244
12,AVAX-USD,9.49,2026-05-21,2026-06-18,9.24,11.34,10.05,0.075869
2,SOL-USD,87.54,2026-05-21,2026-06-18,86.92,101.38,91.84,0.066712
3,ADA-USD,0.25,2026-05-21,2026-06-18,0.25,0.29,0.26,0.066667
6,DOGE-USD,0.11,2026-05-21,2026-06-18,0.09,0.13,0.09,-0.060606
17,MATIC-USD,0.22,2025-03-24,2025-04-21,0.19,0.26,0.17,-0.060606

In [ ]:
df = run_model_nn_cmd('techstock', '0312')
df.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
50,INTA,21.24,2026-05-13,2026-06-10,20.66,27.58,25.00,0.149404
57,MCHP,97.50,2026-05-13,2026-06-10,79.90,96.43,83.53,-0.111590
61,MPWR,1661.12,2026-05-13,2026-06-10,1474.07,1631.50,1341.22,-0.107672
97,TNDM,14.60,2026-05-13,2026-06-10,11.53,14.67,12.93,-0.106621
26,DDOG,201.51,2026-05-13,2026-06-10,200.98,231.00,229.71,0.094553
6,APLD,44.65,2026-05-13,2026-06-10,35.62,47.00,39.82,-0.085928
71,OKTA,78.19,2026-05-13,2026-06-10,76.67,88.37,89.61,0.085603
4,AMBA,82.17,2026-05-13,2026-06-10,80.12,95.02,92.25,0.084702
92,SYNA,133.09,2026-05-13,2026-06-10,107.18,133.02,126.06,-0.082676
47,HUBS,178.10,2026-05-13,2026-06-10,171.82,204.85,200.89,0.080966

In [ ]:
stdf = run_model_nn_cmd('stock', '0227', window_size=40)
# stdf[stdf['predicted_return']>0].head(20)
stdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
64,GLOB,36.89,2026-05-11,2026-06-08,35.55,59.41,40.93,0.227885
53,IONQ,57.24,2026-05-11,2026-06-08,55.78,82.20,70.59,0.214594
130,LFMD,4.55,2026-05-11,2026-06-08,4.28,7.37,4.75,0.201465
372,QUBT,10.22,2026-05-11,2026-06-08,8.98,12.39,14.94,0.184279
303,ESTC,49.97,2026-05-11,2026-06-08,47.98,72.60,55.88,0.177106
358,LAES,3.12,2026-05-11,2026-06-08,2.99,4.54,3.43,0.170940
123,LZ,6.10,2026-05-11,2026-06-08,5.77,8.29,7.29,0.166667
50,Z,40.57,2026-05-11,2026-06-08,38.40,55.31,47.95,0.163914
332,QBTS,24.42,2026-05-11,2026-06-08,23.49,30.93,30.83,0.163664
62,WDAY,121.06,2026-05-11,2026-06-08,116.49,160.88,145.14,0.163363
304,SERV,9.06,2026-05-11,2026-06-08,8.59,11.94,10.98,0.159308
105,SLI,4.18,2026-05-11,2026-06-08,3.99,5.50,4.96,0.152313
111,APP,467.98,2026-05-11,2026-06-08,453.01,636.97,524.95,0.150284
34,UP,5.27,2026-05-11,2026-06-08,4.89,7.91,5.22,0.139785
363,SQNS,3.93,2026-05-11,2026-06-08,3.46,5.15,4.80,0.137405
340,PATH,10.70,2026-05-11,2026-06-08,10.07,14.06,12.33,0.135826
74,SNOW,148.90,2026-05-11,2026-06-08,141.35,198.63,165.60,0.131811
139,UBER,76.53,2026-05-11,2026-06-08,73.94,100.42,85.43,0.131539
205,CMI,699.99,2026-05-11,2026-06-08,537.48,732.57,555.56,-0.130649
208,CSGP,32.68,2026-05-11,2026-06-08,31.80,44.81,34.16,0.129845

In [ ]:
run_model_nn_cmd('buystocks', '0402', False, 500, 250).head(20)
# show_prediction('buystocks', '0508').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
321,AEVA,15.65,2026-03-18,2027-03-03,15.49,31.05,29.89,0.627902
155,INDI,2.61,2026-03-18,2027-03-03,2.63,5.03,4.75,0.584930
355,BITF,2.29,2026-03-18,2027-03-03,2.26,4.37,4.21,0.577875
46,EL,88.15,2026-03-18,2027-03-03,88.84,160.72,164.61,0.566156
228,SLDP,3.13,2026-03-18,2027-03-03,2.65,6.05,5.84,0.548456
148,FIVE,214.07,2026-03-18,2027-03-03,217.66,411.60,363.97,0.546581
93,CHGG,0.58,2026-03-18,2027-03-03,0.55,1.08,1.06,0.545977
324,ENPH,43.53,2026-03-18,2027-03-03,42.38,87.05,71.55,0.539015
194,TGT,115.63,2026-03-18,2027-03-03,112.32,215.84,203.21,0.531811
25,INSG,12.84,2026-03-18,2027-03-03,11.15,23.37,23.99,0.518951
337,WULF,15.53,2026-03-18,2027-03-03,14.48,30.49,25.51,0.512771
342,OPEN,5.36,2026-03-18,2027-03-03,4.65,10.41,9.22,0.509950
34,UP,0.58,2026-03-18,2027-03-03,0.50,1.14,0.97,0.500000
326,PFE,27.33,2026-03-18,2027-03-03,26.13,53.27,43.22,0.495548
76,ETSY,54.72,2026-03-18,2027-03-03,53.47,104.50,86.47,0.489035
80,SKYT,27.62,2026-03-18,2027-03-03,27.71,52.20,42.89,0.482018
276,RVLV,23.21,2026-03-18,2027-03-03,22.06,45.03,35.75,0.476950
48,DOCU,48.09,2026-03-18,2027-03-03,43.27,94.13,74.83,0.471061
240,LYFT,13.69,2026-03-18,2027-03-03,12.58,22.18,25.64,0.470660
327,PATH,12.37,2026-03-18,2027-03-03,11.97,21.64,20.77,0.465373

In [ ]:
run_model_nn_cmd('techstock', '0224', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
96,U,25.92,2026-04-17,2027-04-02,21.17,50.15,48.56,0.541667
76,RBLX,60.34,2026-04-17,2027-04-02,52.27,116.15,109.44,0.534969
95,TWLO,140.11,2026-04-17,2027-04-02,131.98,267.86,239.87,0.521923
61,NET,200.99,2026-04-17,2027-04-02,180.82,378.09,351.54,0.509942
85,SYNA,80.22,2026-04-17,2027-04-02,79.22,155.35,128.30,0.507812
77,RMBS,126.93,2026-04-17,2027-04-02,109.14,244.94,215.40,0.495522
53,MCHP,78.76,2026-04-17,2027-04-02,73.80,147.97,129.81,0.487980
86,TDOC,5.69,2026-04-17,2027-04-02,5.46,10.74,9.08,0.480961
98,UI,1084.50,2026-04-17,2027-04-02,951.24,2118.39,1692.83,0.463796
82,SNOW,143.98,2026-04-17,2027-04-02,138.09,274.08,219.46,0.462310

In [ ]:
run_model_nn_cmd('etf', '0225', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
2,ARKW,139.41,2026-04-20,2027-04-05,117.69,251.18,229.90,0.431676
31,URA,56.05,2026-04-20,2027-04-05,46.44,107.63,82.29,0.405650
0,ARKF,43.81,2026-04-20,2027-04-05,36.98,73.57,65.70,0.341018
1,ARKK,79.32,2026-04-20,2027-04-05,72.77,127.16,113.35,0.316524
50,XME,119.20,2026-04-20,2027-04-05,95.47,205.37,165.99,0.305453
10,ICLN,19.65,2026-04-20,2027-04-05,18.84,29.03,28.75,0.299746
25,ONLN,61.49,2026-04-20,2027-04-05,55.83,88.40,81.22,0.222150
27,SMH,463.96,2026-04-20,2027-04-05,383.77,678.34,624.74,0.211922
19,IYZ,43.23,2026-04-20,2027-04-05,41.36,59.53,55.91,0.209037
51,XNTK,299.03,2026-04-20,2027-04-05,255.51,424.49,393.99,0.197193

In [ ]:
run_model_nn_cmd('bluechipstock', '0117', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
41,UPS,95.79,2026-05-19,2027-05-04,93.63,162.64,153.63,0.426384
33,ORCL,182.38,2026-05-19,2027-05-04,173.16,326.76,266.91,0.401524
37,TMO,450.78,2026-05-19,2027-05-04,434.90,749.91,707.13,0.399012
6,AVGO,409.30,2026-05-19,2027-05-04,345.09,672.68,641.34,0.351177
38,TSLA,396.22,2026-05-19,2027-05-04,349.70,680.84,518.36,0.303064
23,INTC,104.29,2026-05-19,2027-05-04,86.40,171.06,148.74,0.298303
30,NKE,43.06,2026-05-19,2027-05-04,41.07,64.20,62.12,0.295789
18,DIS,103.21,2026-05-19,2027-05-04,98.35,151.93,137.89,0.253658
20,GOOGL,389.02,2026-05-19,2027-05-04,366.51,531.49,521.70,0.216476
14,CSCO,115.62,2026-05-19,2027-05-04,110.97,156.17,153.41,0.212449

In [ ]:
run_model_nn_cmd('pennystock', '0122', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
109,AUID,1.63,2026-02-12,2026-03-12,1.48,2.54,1.86,0.202454
12,CHGG,0.57,2026-02-12,2026-03-12,0.54,0.94,0.54,0.181287
15,CXM,5.39,2026-02-12,2026-03-12,5.23,7.00,6.33,0.147805
64,ALAR,7.22,2026-02-12,2026-03-12,4.98,8.15,5.66,-0.132502
108,MRAM,11.00,2026-02-12,2026-03-12,10.61,13.87,12.87,0.131818
66,IREN,41.04,2026-02-12,2026-03-12,29.70,42.13,35.42,-0.128899
85,WKEY,6.80,2026-02-12,2026-03-12,5.93,9.05,8.04,0.128431
38,ONDS,8.97,2026-02-12,2026-03-12,6.43,10.12,7.13,-0.120030
40,OTLY,11.08,2026-02-12,2026-03-12,9.92,13.37,13.91,0.119134
107,UDMY,4.51,2026-02-12,2026-03-12,4.32,5.82,4.93,0.113821

In [ ]:
run_model_nn_cmd('global', '0226', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
62,ASM,9.10,2026-02-26,2027-02-11,7.98,18.16,17.91,0.613553
43,RYCEF,18.50,2026-02-26,2027-02-11,17.42,36.29,35.73,0.611532
69,NVTS,9.51,2026-02-26,2027-02-11,7.57,18.56,17.82,0.540484
26,KNNGF,74.00,2026-02-25,2027-02-10,68.16,135.48,127.25,0.490495
47,SE,109.23,2026-02-26,2027-02-11,96.75,210.92,177.28,0.479905
61,SIFY,16.10,2026-02-26,2027-02-11,12.72,30.12,28.16,0.469979
45,SFTBY,13.05,2026-02-26,2027-02-11,9.14,24.40,23.71,0.462324
20,FQVLF,29.79,2026-02-26,2027-02-11,28.28,56.88,44.80,0.454179
3,BAK,3.73,2026-02-26,2027-02-11,3.60,6.33,5.94,0.418231
65,KEP,22.26,2026-02-26,2027-02-11,18.67,39.56,36.38,0.416742

In [ ]:
run_model_nn_cmd('country', '0310', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
5,EWA,29.49,2026-05-07,2026-06-04,26.91,29.77,28.21,-0.040466
12,EWT,94.30,2026-05-07,2026-06-04,85.77,95.83,90.13,-0.039484
9,EWC,57.88,2026-05-07,2026-06-04,51.53,59.66,55.72,-0.038758
16,IDX,13.18,2026-05-07,2026-06-04,13.00,13.97,13.89,0.033384
14,EWY,176.73,2026-05-07,2026-06-04,164.96,179.75,170.03,-0.029140
8,EWJ,91.00,2026-05-07,2026-06-04,85.94,92.64,86.50,-0.029011
15,EWZ,38.79,2026-05-07,2026-06-04,36.01,39.57,37.53,-0.028014
6,EWG,42.50,2026-05-07,2026-06-04,39.95,44.07,39.91,-0.028000
24,XCEM,49.37,2026-05-07,2026-06-04,46.06,50.91,47.13,-0.027074
17,ILF,36.14,2026-05-07,2026-06-04,33.98,36.83,34.85,-0.025457

In [ ]:
run_model_nn_cmd('valuestock', '0219', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
86,NUTX,99.59,2026-02-20,2027-02-05,81.31,186.03,192.93,0.540550
113,STRL,433.26,2026-02-20,2027-02-05,315.79,859.64,826.69,0.540353
80,MP,55.18,2026-02-20,2027-02-05,50.21,103.51,97.98,0.520478
24,CCJ,118.41,2026-02-20,2027-02-05,103.98,225.22,203.20,0.498747
96,POWL,539.63,2026-02-20,2027-02-05,431.36,968.34,894.65,0.417237
61,GLW,137.42,2026-02-20,2027-02-05,112.34,238.97,214.61,0.372726
130,WDC,290.10,2026-02-20,2027-02-05,178.91,478.56,493.51,0.322509
30,CLS,296.71,2026-02-20,2027-02-05,219.38,513.79,441.41,0.319560
87,OLN,23.90,2026-02-20,2027-02-05,22.58,37.70,33.63,0.309763
23,CCI,88.12,2026-02-20,2027-02-05,86.67,137.41,118.60,0.296263

In [ ]:
run_model_nn_cmd('crypto', '0223', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
16,AAVE-USD,114.99,2026-02-23,2027-02-08,42.99,154.25,48.05,-0.288953
17,MATIC-USD,0.22,2025-03-24,2026-03-09,0.17,0.41,0.26,0.272727
0,BTC-USD,64800.95,2026-02-23,2027-02-08,24188.92,82484.52,36648.62,-0.262757
3,ADA-USD,0.26,2026-02-23,2027-02-08,0.16,0.49,0.24,0.141026
13,LINK-USD,8.67,2026-02-22,2027-02-07,6.08,15.14,8.39,0.138408
7,FIL-USD,0.89,2026-02-23,2027-02-08,0.45,1.16,0.70,-0.134831
12,AVAX-USD,8.87,2026-02-22,2027-02-07,6.98,16.72,6.46,0.133408
6,DOGE-USD,0.09,2026-02-23,2027-02-08,0.05,0.13,0.06,-0.111111
8,LTC-USD,53.47,2026-02-22,2027-02-07,25.67,95.68,56.87,0.111028
5,DOT-USD,1.27,2026-02-23,2027-02-08,0.68,1.87,0.85,-0.107612

In [ ]:
import sys
sys.path.append('/content')
!ln -s drive/MyDrive/colab/stock_prediction /content/
import stock_prediction.stock_prediction.stock_predictor_lib
from stock_prediction.stock_prediction.stock_predictor_lib import run_model_nn, show_prediction, StockPredictorLib, Config
colab_path = 'content/drive/MyDrive/colab'

In [ ]:
techcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
colab_path = 'content/drive/MyDrive/colab'
techcfg.model_path = f'/{colab_path}/models/transformer/techstock_1220'
techdf = run_model_nn(f'/{colab_path}/tickers/techstocktickers.csv', cfg=techcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/techstock_1220_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/techstock_1220_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/techstock_1220_close_model.pth'}

In [ ]:
techdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
50,INTA,22.25,2026-04-24,2026-05-22,19.76,36.87,31.67,0.322846,0.323811
18,COHR,336.09,2026-04-24,2026-05-22,206.91,338.72,233.11,-0.227647,-0.305709
5,AMKR,78.10,2026-04-24,2026-05-22,51.25,78.38,55.18,-0.211225,-0.291081
102,TWLO,143.79,2026-04-24,2026-05-22,141.97,203.21,183.93,0.226580,0.288740
64,MU,496.72,2026-04-24,2026-05-22,333.53,502.73,338.03,-0.211971,-0.283507
8,ARM,234.81,2026-04-24,2026-05-22,137.84,235.62,177.91,-0.217282,-0.276215
95,TER,418.08,2026-04-24,2026-05-22,263.94,419.26,311.62,-0.206834,-0.275312
83,RMBS,158.40,2026-04-24,2026-05-22,95.57,159.23,119.28,-0.212795,-0.273039
7,APP,448.29,2026-04-24,2026-05-22,286.19,458.77,315.25,-0.211664,-0.266211
61,MPWR,1632.06,2026-04-24,2026-05-22,1072.56,1651.85,1186.68,-0.201196,-0.263680

In [ ]:
techrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
techrcfg.model_path = f'/{colab_path}/models/rolling/techstock_0109'
techrdf = run_model_nn(f'/{colab_path}/tickers/techstocktickers.csv', cfg=techrcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/techstock_0109_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/techstock_0109_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/techstock_0109_close_model.pth'}

In [ ]:
techrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
45,HIMS,30.56,2026-04-24,2026-05-22,27.19,42.00,35.92,0.146488,0.107888
71,OKTA,75.98,2026-04-24,2026-05-22,58.49,79.53,66.66,-0.102044,-0.091354
74,PANW,178.54,2026-04-24,2026-05-22,150.20,189.86,140.73,-0.102367,-0.087911
59,MNDY,67.79,2026-04-24,2026-05-22,62.46,87.67,74.90,0.106505,0.074714
3,ALAB,212.84,2026-04-24,2026-05-22,201.57,245.19,241.77,0.078322,0.065921
41,FOUR,45.29,2026-04-24,2026-05-22,43.11,53.55,49.79,0.077869,0.063608
7,APP,448.29,2026-04-24,2026-05-22,403.93,574.61,499.92,0.099333,0.063316
15,CEG,313.53,2026-04-24,2026-05-22,250.44,328.19,289.24,-0.077313,-0.059042
25,DBX,24.02,2026-04-24,2026-05-22,22.69,29.86,25.16,0.078407,0.049653
64,MU,496.72,2026-04-24,2026-05-22,471.82,569.44,544.67,0.064268,0.049517

In [ ]:
defetfcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
defetfcfg.model_path = f'/{colab_path}/models/rolling/etf_1221'
etfdf = run_model_nn(f'/{colab_path}/tickers/etftickers.csv', cfg=defetfcfg)
etfdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/etf_1221_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/etf_1221_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/etf_1221_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
22,XLC,116.91,2026-01-27,2026-02-24,114.02,121.17,127.73,0.034756
21,XLB,49.99,2026-01-27,2026-02-24,48.59,53.51,52.07,0.028006
0,ARKF,46.05,2026-01-27,2026-02-24,45.11,49.12,47.49,0.025841
31,XME,128.38,2026-01-27,2026-02-24,125.85,138.44,128.85,0.020772
19,URA,57.85,2026-01-27,2026-02-24,56.05,63.46,57.59,0.020455
3,DIA,490.07,2026-01-27,2026-02-24,479.53,513.22,507.28,0.020283
28,XLU,43.41,2026-01-27,2026-02-24,40.92,44.09,42.89,-0.017891
16,QQQ,631.13,2026-01-27,2026-02-24,615.90,651.98,656.09,0.016151
8,IXC,46.34,2026-01-27,2026-02-24,45.23,48.58,47.37,0.015537
15,JXI,81.94,2026-01-27,2026-02-24,77.62,83.46,81.52,-0.013099

In [ ]:
tvolcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
tvolcfg.model_path = f'/{colab_path}/models/transformer/pennystock_1226'
tvoldf = run_model_nn(f'/{colab_path}/tickers/pennystocktickers.csv', cfg=tvolcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/pennystock_1226_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/pennystock_1226_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/pennystock_1226_close_model.pth'}

In [ ]:
tvoldf[tvoldf['predicted_return']> 0].head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
2,AMSSY,5.74,2026-02-24,2026-03-24,5.63,8.61,15.48,0.725900
54,SLE,3.49,2026-02-25,2026-03-25,3.42,6.82,3.86,0.346705
91,PETS,2.79,2026-02-25,2026-03-25,2.75,4.56,3.10,0.243728
89,GPRO,0.84,2026-02-25,2026-03-25,0.74,1.16,1.10,0.190476
109,AUID,1.50,2026-02-25,2026-03-25,1.25,1.96,2.12,0.184444
6,ATOM,5.74,2026-02-25,2026-03-25,4.16,8.66,7.40,0.174216
90,DNUT,2.99,2026-02-25,2026-03-25,2.80,3.95,3.22,0.111483
31,LFMD,2.69,2026-02-25,2026-03-25,2.61,3.49,2.81,0.104089
69,BNED,8.32,2026-02-25,2026-03-25,4.69,12.04,10.64,0.096554
28,INVZ,0.85,2026-02-25,2026-03-25,0.72,1.19,0.87,0.090196

In [ ]:
tvolrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
tvolrcfg.model_path = f'/{colab_path}/models/rolling/pennystock_0114'
tvolrdf = run_model_nn(f'/{colab_path}/tickers/pennystocktickers.csv', cfg=tvolrcfg)

In [ ]:
tvolrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
19,FSLY,25.20,2026-03-20,2026-04-17,19.92,41.69,34.39,0.269841
2,AMSSY,5.10,2026-03-20,2026-04-17,4.68,7.22,7.38,0.260131
8,AXTI,54.24,2026-03-20,2026-04-17,46.72,75.46,72.43,0.195981
75,TSSI,10.95,2026-03-20,2026-04-17,9.08,16.40,13.12,0.175038
79,ACFN,18.12,2026-03-20,2026-04-17,16.97,24.39,22.45,0.173841
81,AEHR,34.52,2026-03-20,2026-04-17,30.58,51.69,38.93,0.170336
37,NNOX,2.41,2026-03-20,2026-04-17,2.26,2.95,3.20,0.163209
74,TGEN,2.23,2026-03-20,2026-04-17,2.03,3.15,2.51,0.149477
92,GDRX,2.03,2026-03-20,2026-04-17,1.93,2.81,2.26,0.149425
10,BLNK,0.56,2026-03-20,2026-04-17,0.55,0.69,0.69,0.148810

In [ ]:
tbvolcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
tbvolcfg.model_path = f'/{colab_path}/models/transformer_base/pennystock_0417'
tbvoldf = run_model_nn(f'/{colab_path}/tickers/pennystocktickers.csv', cfg=tbvolcfg)

In [ ]:
tbvoldf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
50,RVYL,6.41,2026-04-17,2026-05-15,5.05,6.77,5.90,-0.078523,-0.056285
73,EOSE,7.15,2026-04-17,2026-05-15,6.37,9.84,7.41,0.101166,0.050327
0,ALSMY,1.91,2026-04-17,2026-05-15,1.77,2.40,1.98,0.073298,0.039180
19,FSLY,24.45,2026-04-17,2026-05-15,18.18,28.42,21.29,-0.074438,-0.031605
70,FUBO,13.18,2026-04-17,2026-05-15,9.40,15.02,12.47,-0.067021,-0.025766
55,SMWB,2.62,2026-04-17,2026-05-15,2.34,3.37,2.65,0.063613,0.024573
17,EVGO,2.19,2026-04-17,2026-05-15,2.00,2.68,2.23,0.051750,0.020768
10,BLNK,0.70,2026-04-17,2026-05-15,0.57,0.76,0.67,-0.047619,-0.020454
101,GPUS,0.16,2026-04-17,2026-05-15,0.13,0.22,0.16,0.062500,0.016704
46,PTON,5.03,2026-04-17,2026-05-15,4.35,5.41,4.78,-0.036448,-0.015351

In [ ]:
bctcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
bctcfg.model_path = f'/{colab_path}/models/transformer/bluechipstock_0328'
bctdf = run_model_nn(f'/{colab_path}/tickers/bluechipstocktickers.csv', cfg=bctcfg)
bctdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/bluechipstock_0328_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/bluechipstock_0328_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/bluechipstock_0328_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
27,META,525.72,2026-03-27,2026-04-24,499.04,597.66,613.61,0.084424
34,PYPL,43.59,2026-03-27,2026-04-24,42.60,50.61,48.42,0.083047
37,TMO,473.36,2026-03-27,2026-04-24,461.29,537.60,534.63,0.079883
36,SBUX,86.81,2026-03-27,2026-04-24,83.54,98.71,96.34,0.069731
1,ACN,192.60,2026-03-27,2026-04-24,188.49,211.84,216.90,0.068242
8,BKNG,4062.14,2026-03-27,2026-04-24,4002.21,4724.27,4271.65,0.066608
26,LLY,878.24,2026-03-27,2026-04-24,847.94,985.07,960.48,0.060261
23,INTC,43.13,2026-03-27,2026-04-24,36.76,45.59,39.63,-0.057269
19,FDX,343.97,2026-03-27,2026-04-24,303.25,348.78,320.88,-0.057176
33,ORCL,139.66,2026-03-27,2026-04-24,137.70,148.83,154.53,0.052699

In [ ]:
bcrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
bcrcfg.model_path = f'/{colab_path}/models/rolling/bluechipstock_0117'
bcrdf = run_model_nn(f'/{colab_path}/tickers/bluechipstocktickers.csv', cfg=bcrcfg)
bcrdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/bluechipstock_0117_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/bluechipstock_0117_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/bluechipstock_0117_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
14,CSCO,78.43,2026-02-26,2026-03-26,71.19,80.25,69.55,-0.060776
25,KO,80.25,2026-02-26,2026-03-26,78.57,90.78,85.56,0.058816
15,DE,620.78,2026-02-26,2026-03-26,607.38,703.49,655.81,0.056026
8,BKNG,4268.91,2026-02-26,2026-03-26,3543.37,4446.64,4099.32,-0.056017
5,ANET,130.25,2026-02-26,2026-03-26,124.23,150.03,137.54,0.053871
23,IBM,244.44,2026-02-26,2026-03-26,227.92,267.40,274.73,0.050087
33,ORCL,148.46,2026-02-26,2026-03-26,138.79,166.40,159.95,0.044367
9,BRK-B,499.40,2026-02-26,2026-03-26,484.76,553.69,521.03,0.040902
7,BA,228.42,2026-02-26,2026-03-26,223.73,252.98,236.35,0.040569
39,TXN,213.21,2026-02-26,2026-03-26,205.29,232.98,226.08,0.038647

In [ ]:
buystkcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
buystkcfg.model_path = f'/{colab_path}/models/transformer/buystocks_0123'
buystkcfg.model.window_size = 500
buystkcfg.model.future_days = 250
buystkdf = run_model_nn(f'/{colab_path}/tickers/buystockstickers.csv', cfg=buystkcfg)

In [ ]:
buystkdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
16,INVZ,0.66,2026-04-20,2027-04-05,0.63,12.07,4.87,7.873737,8.664886
268,CRNC,9.00,2026-04-20,2027-04-05,8.23,95.35,78.48,5.742963,7.868080
85,RIVN,16.92,2026-04-20,2027-04-05,13.76,139.60,79.95,3.596336,4.257771
8,SFIX,4.07,2026-04-20,2027-04-05,3.86,23.91,13.26,2.360360,2.768415
53,LCID,6.75,2026-04-20,2027-04-05,6.81,34.28,19.65,1.999506,2.404690
380,CTRM,1.81,2026-04-20,2027-04-05,1.61,7.30,6.05,1.755064,2.283454
15,OUST,27.14,2026-04-20,2027-04-05,13.39,108.15,116.28,1.920904,2.144180
348,OPEN,5.35,2026-04-20,2027-04-05,4.94,21.94,15.56,1.644237,2.062779
26,BNED,10.97,2026-04-20,2027-04-05,10.14,13.35,101.19,2.788514,2.022055
156,INDI,3.39,2026-04-20,2027-04-05,3.25,12.83,9.49,1.514258,1.957834
33,UP,0.39,2026-04-20,2027-04-05,0.33,1.32,1.25,1.478632,1.890230
372,ABAT,3.47,2026-04-20,2027-04-05,3.43,15.37,7.90,1.564841,1.725120
250,WKEY,7.76,2026-04-20,2027-04-05,7.26,39.02,14.98,1.631443,1.527156
62,GLOB,50.60,2026-04-20,2027-04-05,50.58,131.57,131.47,1.066008,1.507003
328,ENPH,33.88,2026-04-20,2027-04-05,33.72,64.76,152.58,1.470091,1.454627
352,SQNS,2.65,2026-04-20,2027-04-05,2.41,14.24,4.25,1.628931,1.352848
220,PAGS,11.32,2026-04-20,2027-04-05,8.34,29.92,34.32,1.137220,1.289510
27,AI,9.38,2026-04-20,2027-04-05,8.55,25.09,22.61,0.998934,1.285150
76,ETSY,64.18,2026-04-20,2027-04-05,49.70,153.63,194.71,1.067311,1.198038
30,TEAM,71.48,2026-04-20,2027-04-05,70.59,180.17,152.87,0.882251,1.194584

In [ ]:
buystkrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
buystkrcfg.model_path = f'/{colab_path}/models/rolling/buystocks_1213'
buystkrcfg.model.window_size = 500
buystkrcfg.model.future_days = 250
buystkrdf = run_model_nn(f'/{colab_path}/tickers/buystockstickers.csv', cfg=buystkrcfg)

In [ ]:
buystkrdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
350,SQNS,2.41,2026-04-02,2027-03-18,2.18,7.28,3.17,0.746888
7,HIMS,19.24,2026-04-02,2027-03-18,18.21,49.25,32.37,0.729556
247,BYRN,9.11,2026-04-02,2027-03-18,8.60,20.99,15.77,0.659715
31,TEAM,68.83,2026-04-02,2027-03-18,66.35,201.89,65.50,0.616253
168,TTD,22.19,2026-04-02,2027-03-18,20.73,40.50,40.57,0.529217
17,INVZ,0.66,2026-04-02,2027-03-18,0.63,1.55,0.84,0.525253
5,DOMO,2.87,2026-04-02,2027-03-18,2.77,6.67,3.56,0.509872
22,MBLY,7.39,2026-04-02,2027-03-18,6.70,18.22,7.74,0.473162
120,LZ,5.74,2026-04-02,2027-03-18,5.50,12.22,7.48,0.463415
93,CHGG,0.75,2026-04-02,2027-03-18,0.64,1.33,1.32,0.462222
34,UP,0.50,2026-04-02,2027-03-18,0.47,1.01,0.70,0.453333
156,NOW,101.82,2026-04-02,2027-03-18,99.20,226.68,115.81,0.445983
111,CNSWF,1777.48,2026-04-02,2027-03-18,1633.38,3772.25,2040.75,0.396430
166,SWKS,54.08,2026-04-02,2027-03-18,50.09,117.94,57.49,0.390039
0,SE,81.51,2026-04-02,2027-03-18,73.73,185.03,80.98,0.389359
176,ACN,198.65,2026-04-02,2027-03-18,181.23,362.51,278.97,0.380502
349,INMD,13.75,2026-04-02,2027-03-18,12.04,22.47,22.10,0.372364
19,ADBE,241.73,2026-04-02,2027-03-18,234.84,375.59,383.98,0.371241
187,GDYN,5.69,2026-04-02,2027-03-18,5.23,11.02,7.13,0.369654
75,NVO,36.49,2026-04-02,2027-03-18,33.73,57.69,56.34,0.349776

In [ ]:
stkcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
stkcfg.model_path = f'/{colab_path}/models/transformer/stock_0105'
stkdf = run_model_nn(f'/{colab_path}/tickers/stocktickers.csv', cfg=stkcfg)

In [ ]:
# stkdf[stkdf['predicted_return'] > 0].head(20)
stkdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
336,ENPH,33.88,2026-04-20,2026-05-18,30.49,66.07,51.17,0.453463,0.477524
387,SKM,38.11,2026-04-20,2026-05-18,25.67,38.67,22.43,-0.241057,-0.315559
290,KEYS,335.14,2026-04-20,2026-05-18,163.31,344.48,233.91,-0.262298,-0.309252
221,COHR,347.51,2026-04-20,2026-05-18,174.31,371.67,208.89,-0.275925,-0.307461
327,MU,448.42,2026-04-20,2026-05-18,253.35,463.16,294.98,-0.248108,-0.304342
367,TTMI,125.81,2026-04-20,2026-05-18,67.67,131.07,86.11,-0.245291,-0.284285
20,STX,539.75,2026-04-20,2026-05-18,349.13,557.87,360.21,-0.217409,-0.266040
100,AEHR,90.15,2026-04-20,2026-05-18,52.98,94.71,60.18,-0.231392,-0.265016
70,NOK,10.60,2026-04-20,2026-05-18,7.72,10.84,6.67,-0.206604,-0.255494
203,AGX,611.21,2026-04-20,2026-05-18,429.92,636.46,373.43,-0.214776,-0.249384
301,BE,218.27,2026-04-20,2026-05-18,131.28,233.70,141.40,-0.226676,-0.243377
321,PSIX,78.59,2026-04-20,2026-05-18,48.36,81.24,58.53,-0.202061,-0.233451
31,TEAM,71.48,2026-04-20,2026-05-18,67.23,113.60,86.12,0.244870,0.225126
407,SOL-USD,85.71,2026-04-20,2026-05-18,78.74,135.71,104.12,0.238945,0.209990
386,EWY,150.09,2026-04-20,2026-05-18,110.97,153.92,110.90,-0.165412,-0.202663
55,HUBS,229.88,2026-04-20,2026-05-18,218.78,320.42,281.91,0.190636,0.199395
46,EL,77.85,2026-04-20,2026-05-18,73.38,100.75,102.39,0.183986,0.198057
389,NAK,2.12,2026-04-20,2026-05-18,1.32,2.24,1.63,-0.183962,-0.187723
122,LZ,6.57,2026-04-20,2026-05-18,6.32,8.71,8.00,0.168442,0.186011
223,LSCC,118.83,2026-04-20,2026-05-18,89.10,123.85,84.54,-0.165503,-0.185410

In [ ]:
stkrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
stkrcfg.model_path = f'/{colab_path}/models/rolling/stock_0102'
stkrdf = run_model_nn(f'/{colab_path}/tickers/stocktickers.csv', cfg=stkrcfg)

In [ ]:
# stkrdf[stkrdf['predicted_return'] > 0].head(20)
stkrdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
100,AEHR,73.22,2026-04-15,2026-05-13,65.94,94.83,105.12,0.210462,0.195550
226,COHR,308.20,2026-04-15,2026-05-13,287.17,400.05,394.61,0.170052,0.171467
372,CRCL,105.52,2026-04-15,2026-05-13,76.04,112.26,83.83,-0.140353,-0.133532
261,LUNR,23.88,2026-04-15,2026-05-13,22.37,32.14,27.81,0.149079,0.132774
263,PRGS,29.57,2026-04-15,2026-05-13,22.46,31.85,24.15,-0.115545,-0.096598
255,EOSE,7.08,2026-04-15,2026-05-13,5.06,7.71,5.88,-0.121940,-0.095035
245,IESC,529.22,2026-04-15,2026-05-13,509.95,723.44,552.48,0.124844,0.089400
137,STRL,456.08,2026-04-15,2026-05-13,431.90,543.14,524.43,0.095912,0.086269
374,CDE,19.67,2026-04-15,2026-05-13,15.34,21.33,15.95,-0.108287,-0.085697
371,TTMI,116.60,2026-04-15,2026-05-13,106.43,159.01,128.16,0.125214,0.084741
190,U,25.26,2026-04-15,2026-05-13,20.88,26.76,21.00,-0.094220,-0.081721
338,AEVA,14.93,2026-04-15,2026-05-13,10.72,16.36,12.71,-0.111632,-0.079662
173,TTD,22.38,2026-04-15,2026-05-13,15.50,24.93,18.82,-0.117516,-0.079135
135,CLS,381.94,2026-04-15,2026-05-13,353.65,439.85,466.03,0.099239,0.078347
138,CAAP,26.33,2026-04-15,2026-05-13,25.33,31.51,28.96,0.086213,0.077177
330,ROOT,51.70,2026-04-15,2026-05-13,43.83,55.12,42.92,-0.085300,-0.067790
256,FLEX,78.43,2026-04-15,2026-05-13,68.42,105.53,87.43,0.110884,0.063645
33,VALE,17.62,2026-04-15,2026-05-13,16.81,20.28,19.61,0.072645,0.061868
380,EWY,144.92,2026-04-15,2026-05-13,118.77,154.02,127.89,-0.078388,-0.059609
45,RMBS,120.02,2026-04-15,2026-05-13,113.81,134.06,137.84,0.071238,0.057731

In [ ]:
glbcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
glbcfg.model_path = f'/{colab_path}/models/transformer/global_0105'
glbdf = run_model_nn(f'/{colab_path}/tickers/globaltickers.csv', cfg=glbcfg)

In [ ]:
glbdf[glbdf['predicted_return']>0].head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
9,BAK,3.63,2026-04-20,2026-05-18,3.49,5.27,4.17,0.187328,0.173690
39,GLOB,50.60,2026-04-20,2026-05-18,49.91,61.22,57.98,0.114032,0.138356
45,KLAR,14.90,2026-04-20,2026-05-18,14.46,17.09,18.12,0.111186,0.119528
64,PDD,104.20,2026-04-20,2026-05-18,98.07,122.62,114.80,0.073225,0.054560
48,LND,4.02,2026-04-20,2026-05-18,3.76,4.64,4.45,0.065506,0.045623
74,SE,89.34,2026-04-20,2026-05-18,85.30,112.18,88.99,0.068838,0.035584
66,PROSF,48.02,2026-04-15,2026-05-13,45.37,52.35,52.42,0.042205,0.025865
3,ALSMY,1.96,2026-04-20,2026-05-18,1.66,2.14,2.46,0.064626,0.024899
22,DNNGY,8.18,2026-04-20,2026-05-18,8.01,9.22,8.25,0.038305,0.022945
27,EDNMY,12.00,2026-04-17,2026-05-15,10.76,13.62,13.27,0.045833,0.019790

In [ ]:
glbrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
glbrcfg.model_path = f'/{colab_path}/models/rolling/global_1210'
glbrdf = run_model_nn(f'/{colab_path}/tickers/globaltickers.csv', cfg=glbrcfg)

In [ ]:
glbrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
27,EDNMF,21.00,2026-04-08,2026-05-06,20.18,28.45,29.13,0.234286,0.283335
7,AUNA,5.52,2026-04-20,2026-05-18,5.42,6.22,6.62,0.102657,0.116604
22,DNNGY,8.18,2026-04-20,2026-05-18,7.97,9.16,9.13,0.070090,0.072531
50,MELI,1870.08,2026-04-20,2026-05-18,1742.77,1931.90,1532.42,-0.071860,-0.059184
40,HENKY,18.31,2026-04-20,2026-05-18,16.26,18.70,17.01,-0.053887,-0.052102
52,NHYDY,11.31,2026-04-20,2026-05-18,10.68,12.82,12.42,0.058650,0.041878
37,GLCNF,7.38,2026-04-17,2026-05-15,7.09,8.42,7.71,0.048780,0.032318
0,ADDDF,170.93,2026-04-17,2026-05-15,171.44,178.42,174.21,0.021997,0.028822
17,CPA,125.30,2026-04-20,2026-05-18,118.33,128.32,116.16,-0.034823,-0.028694
36,FQVLF,28.88,2026-04-20,2026-05-18,25.75,30.03,27.31,-0.040974,-0.027415

In [ ]:
ctcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
ctcfg.model_path = f'/{colab_path}/models/transformer/country_1211'
ctdf = run_model_nn(f'/{colab_path}/tickers/countrytickers.csv', cfg=ctcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/country_1211_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/country_1211_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/country_1211_close_model.pth'}

In [ ]:
ctdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
16,IDX,13.94,2026-04-08,2026-05-06,13.98,15.54,15.49,0.076279
7,EWI,56.62,2026-04-08,2026-05-06,48.92,56.93,55.32,-0.051160
4,EPHE,25.71,2026-04-08,2026-05-06,24.81,28.84,26.58,0.040192
8,EWJ,89.41,2026-04-08,2026-05-06,80.42,89.88,87.66,-0.038288
5,EWA,29.52,2026-04-08,2026-05-06,27.35,29.65,28.39,-0.035795
11,EWP,57.36,2026-04-08,2026-05-06,51.87,58.21,55.99,-0.034926
24,XCEM,43.96,2026-04-08,2026-05-06,40.17,44.90,42.25,-0.034577
9,EWC,56.64,2026-04-08,2026-05-06,52.10,57.21,54.84,-0.033957
12,EWT,76.36,2026-04-08,2026-05-06,69.82,77.17,74.35,-0.033787
2,FLN,26.63,2026-04-08,2026-05-06,24.51,26.84,25.88,-0.033296

In [ ]:
ctycfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
ctycfg.model_path = f'/{colab_path}/models/transformer/country_0303'
ctycfg.model.window_size = 500
ctycfg.model.future_days = 250
ctydf = run_model_nn(f'/{colab_path}/tickers/countrytickers.csv', cfg=ctycfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/country_0303_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/country_0303_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/country_0303_close_model.pth'}

In [ ]:
ctydf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
19,KEMQ,23.42,2026-03-03,2027-02-16,20.89,31.46,29.76,0.168659
18,INDA,50.25,2026-03-03,2027-02-16,49.39,62.75,63.98,0.168292
12,EWT,71.72,2026-03-03,2027-02-16,52.00,73.36,59.22,-0.142127
10,EWM,28.43,2026-03-03,2027-02-16,19.90,28.34,25.31,-0.137648
14,EWY,134.43,2026-03-03,2027-02-16,86.88,136.88,124.36,-0.136800
5,EWA,29.19,2026-03-03,2027-02-16,22.75,30.97,23.31,-0.120361
8,EWJ,87.00,2026-03-03,2027-02-16,66.87,89.01,74.22,-0.118391
3,ECH,39.46,2026-03-03,2027-02-16,28.12,39.76,36.91,-0.114800
24,XCEM,42.62,2026-03-03,2027-02-16,31.83,43.48,38.49,-0.109964
2,FLN,25.02,2026-03-03,2027-02-16,18.75,25.38,22.96,-0.106182

In [ ]:
etftbcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
etftbcfg.model_path = f'/{colab_path}/models/transformer_base/etf_0420'
etftbcfg.model.window_size = 500
etftbcfg.model.future_days = 250
etftbdf = run_model_nn(f'/{colab_path}/tickers/etftickers.csv', cfg=etftbcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer_base/etf_0420_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer_base/etf_0420_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer_base/etf_0420_close_model.pth'}

In [ ]:
etftbdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
1,ARKK,79.32,2026-04-20,2027-04-05,69.77,157.69,149.96,0.586065,0.685400
4,DAPP,19.52,2026-04-20,2027-04-05,15.50,29.83,42.04,0.491974,0.435590
49,XLV,147.42,2026-04-20,2027-04-05,143.88,169.62,188.70,0.135531,0.147450
42,XLE,55.07,2026-04-20,2027-04-05,52.84,66.49,63.73,0.108044,0.109092
17,IXC,52.76,2026-04-20,2027-04-05,48.93,63.92,62.22,0.106078,0.088587
39,XITK,171.49,2026-04-20,2027-04-05,119.21,191.98,140.97,-0.121115,-0.082483
28,SMH,463.96,2026-04-20,2027-04-05,324.59,487.47,429.60,-0.107926,-0.080161
0,ARKF,43.81,2026-04-20,2027-04-05,37.28,52.32,57.87,0.122042,0.075016
11,ICLN,19.65,2026-04-20,2027-04-05,16.39,23.24,25.68,0.107888,0.058162
2,ARKW,139.41,2026-04-20,2027-04-05,114.88,169.25,179.51,0.108577,0.057952

In [ ]:
crcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
crcfg.model_path = f'/{colab_path}/models/rolling/country_0310'
crdf = run_model_nn(f'/{colab_path}/tickers/countrytickers.csv', cfg=crcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/country_0310_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/country_0310_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/country_0310_close_model.pth'}

In [ ]:
crdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
10,EWM,28.86,2026-04-08,2026-05-06,28.03,30.64,30.75,0.032802
15,EWZ,39.57,2026-04-08,2026-05-06,37.32,40.17,38.36,-0.024092
4,EPHE,25.71,2026-04-08,2026-05-06,24.56,26.34,24.59,-0.021263
13,EWW,79.11,2026-04-08,2026-05-06,74.44,80.55,77.49,-0.020436
2,FLN,26.63,2026-04-08,2026-05-06,25.46,27.05,25.90,-0.018525
23,VNM,18.42,2026-04-08,2026-05-06,17.89,19.36,19.03,0.018458
8,EWJ,89.41,2026-04-08,2026-05-06,84.34,91.10,88.80,-0.014875
18,INDA,49.27,2026-04-08,2026-05-06,46.45,51.50,51.88,0.013666
11,EWP,57.36,2026-04-08,2026-05-06,54.38,58.57,56.81,-0.013482
17,ILF,36.79,2026-04-08,2026-05-06,34.93,37.62,36.37,-0.013138

In [ ]:
valtcfg = Config.from_file('./stock_prediction/configs/experiment.yaml')
valtcfg.model_path = f'/{colab_path}/models/transformer/valuestock_1018'
valtdf = run_model_nn(f'valuestocktickers.csv', cfg=valtcfg)

In [ ]:
valtdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
71,POWL,355.91,2025-11-12,2025-12-10,318.63,406.16,497.69,0.144934
16,CC,12.51,2025-11-12,2025-12-10,11.58,15.90,14.90,0.129230
7,ARE,53.86,2025-11-12,2025-12-10,52.99,59.89,66.73,0.111586
91,UAL,99.94,2025-11-12,2025-12-10,91.43,119.48,121.23,0.107798
14,BXC,57.66,2025-11-12,2025-12-10,55.51,69.67,63.39,0.090126
44,GLW,88.71,2025-11-12,2025-12-10,86.23,108.45,94.80,0.087739
74,RH,160.72,2025-11-12,2025-12-10,156.87,193.12,172.52,0.083686
37,F,13.45,2025-11-12,2025-12-10,12.72,13.75,10.53,-0.083024
58,MOD,147.99,2025-11-12,2025-12-10,142.12,179.25,154.26,0.071311
39,FICO,1778.19,2025-11-12,2025-12-10,1648.44,2256.72,1784.05,0.066480

In [ ]:
valrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
valrcfg.model_path = f'/{colab_path}/models/rolling/valuestock_0106'
valrdf = run_model_nn(f'/{colab_path}/tickers/valuestocktickers.csv', cfg=valrcfg)

In [ ]:
valrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
28,CLS,361.54,2026-04-28,2026-05-26,348.75,444.06,446.67,0.142778,0.161779
34,CTAS,174.22,2026-04-28,2026-05-26,156.80,176.16,160.74,-0.055409,-0.064027
2,ADI,383.26,2026-04-28,2026-05-26,356.32,435.06,449.95,0.079624,0.059149
66,IPI,37.53,2026-04-28,2026-05-26,34.86,43.99,42.13,0.074518,0.052902
24,CEG,305.71,2026-04-28,2026-05-26,294.90,353.88,323.71,0.060362,0.046256
37,DAL,67.22,2026-04-28,2026-05-26,65.71,72.74,72.70,0.047059,0.045048
79,MP,61.70,2026-04-28,2026-05-26,58.08,74.62,64.43,0.064992,0.038254
21,CC,25.70,2026-04-28,2026-05-26,22.20,27.12,23.51,-0.055383,-0.037890
73,LULU,142.39,2026-04-28,2026-05-26,138.99,165.76,145.77,0.054662,0.037440
60,GWW,1160.14,2026-04-28,2026-05-26,1117.82,1294.93,1236.78,0.048589,0.037158

In [ ]:
commtcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
commtcfg.model_path = f'/{colab_path}/models/transformer/commodity_0109'
commtdf = run_model_nn(f'/{colab_path}/tickers/commoditytickers.csv', cfg=commtcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/commodity_0109_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/commodity_0109_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/commodity_0109_close_model.pth'}

In [ ]:
commtdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
5,GLD,434.53,2026-04-08,2026-05-06,352.30,432.66,422.14,-0.074019
8,SLV,67.47,2026-04-08,2026-05-06,59.86,66.41,62.03,-0.069710
0,DBC,28.56,2026-04-08,2026-05-06,25.85,28.98,27.95,-0.033847
2,FXE,107.69,2026-04-08,2026-05-06,104.99,108.25,101.93,-0.024453
7,PALL,142.43,2026-04-08,2026-05-06,131.41,152.85,138.02,-0.011725
9,SOYB,24.36,2026-04-08,2026-05-06,23.76,24.75,23.94,-0.008621
12,USO,124.58,2026-04-08,2026-05-06,122.05,135.94,112.76,-0.008000
1,FXB,128.91,2026-04-08,2026-05-06,126.77,129.72,128.40,-0.004758
13,UUP,27.53,2026-04-08,2026-05-06,27.38,27.95,27.64,0.004601
3,FXF,111.61,2026-04-08,2026-05-06,110.45,112.29,110.66,-0.004271

In [ ]:
commtbcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
commtbcfg.model_path = f'/{colab_path}/models/transformer_base/commodity_0410'
commtbdf = run_model_nn(f'/{colab_path}/tickers/commoditytickers.csv', cfg=commtbcfg)
commtbdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer_base/commodity_0410_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer_base/commodity_0410_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer_base/commodity_0410_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
4,FXY,57.70,2026-04-09,2026-05-07,57.55,60.19,62.51,0.041306,1.176190
13,UUP,27.48,2026-04-09,2026-05-07,27.48,27.88,27.53,0.005459,0.842927
0,DBC,28.71,2026-04-09,2026-05-07,28.06,29.95,30.61,0.028910,0.768058
12,USO,126.96,2026-04-09,2026-05-07,122.10,133.35,140.58,0.039776,0.664151
10,TIP,110.96,2026-04-09,2026-05-07,109.62,111.74,109.64,-0.005648,-0.630008
15,WEAT,22.01,2026-04-09,2026-05-07,21.99,23.53,21.84,0.020142,0.580449
6,ISHG,75.36,2026-04-09,2026-05-07,74.37,76.34,73.34,-0.008979,-0.543672
14,VTIP,50.03,2026-04-09,2026-05-07,49.79,50.50,50.27,0.003131,0.529664
7,PALL,141.65,2026-04-09,2026-05-07,138.39,147.07,129.84,-0.022709,-0.457291
3,FXF,111.65,2026-04-09,2026-05-07,107.79,112.68,111.93,-0.007613,-0.395293

In [ ]:
commrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
commrcfg.model_path = f'/{colab_path}/models/rolling/commodity_0312'
commrdf = run_model_nn(f'/{colab_path}/tickers/commoditytickers.csv', cfg=commrcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/commodity_0312_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/commodity_0312_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/commodity_0312_close_model.pth'}

In [ ]:
commrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
5,GLD,423.75,2026-04-30,2026-05-28,417.00,457.81,437.58,0.032362,0.026637
12,USO,145.10,2026-04-30,2026-05-28,127.34,147.50,146.06,-0.033081,-0.017292
11,TLT,85.76,2026-04-30,2026-05-28,84.83,87.56,89.52,0.017996,0.014441
13,UUP,27.38,2026-04-30,2026-05-28,27.18,28.24,27.97,0.015218,0.014098
6,ISHG,75.95,2026-04-30,2026-05-28,75.54,77.05,78.75,0.015317,0.013589
9,SOYB,24.77,2026-04-30,2026-05-28,24.22,25.20,23.89,-0.013457,-0.008063
0,DBC,30.88,2026-04-30,2026-05-28,28.65,31.45,31.01,-0.016516,-0.006851
4,FXY,58.69,2026-04-30,2026-05-28,56.85,59.31,58.21,-0.009655,-0.005438
10,TIP,111.50,2026-04-30,2026-05-28,111.13,112.04,113.51,0.006517,0.004830
7,PALL,138.36,2026-04-30,2026-05-28,133.29,148.62,139.29,0.014744,0.004769

In [ ]:
cryptcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
cryptcfg.model_path = f'/{colab_path}/models/transformer_base/crypto_0415'
cryptdf = run_model_nn(f'/{colab_path}/tickers/cryptotickers.csv', cfg=cryptcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer_base/crypto_0415_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer_base/crypto_0415_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer_base/crypto_0415_close_model.pth'}

In [ ]:
cryptdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
17,MATIC-USD,0.22,2025-03-24,2025-04-21,0.15,0.23,0.16,-0.181818,-0.204346
13,LINK-USD,9.07,2026-04-15,2026-05-13,8.78,11.34,11.73,0.170526,0.201573
10,BCH-USD,435.47,2026-04-15,2026-05-13,430.44,676.57,461.04,0.200274,0.159470
6,DOGE-USD,0.09,2026-04-15,2026-05-13,0.09,0.10,0.10,0.074074,0.104757
1,ETH-USD,2331.67,2026-04-15,2026-05-13,1846.80,2454.00,2032.68,-0.094572,-0.082095
11,ICP-USD,2.42,2026-04-15,2026-05-13,2.20,2.85,2.88,0.092287,0.065697
4,XRP-USD,1.36,2026-04-15,2026-05-13,1.25,1.57,1.49,0.056373,0.031785
8,LTC-USD,54.16,2026-04-15,2026-05-13,53.59,63.47,53.37,0.048929,0.027528
3,ADA-USD,0.24,2026-04-15,2026-05-13,0.23,0.29,0.23,0.041667,0.014731
5,DOT-USD,1.17,2026-04-15,2026-05-13,1.12,1.49,1.03,0.037037,0.008063

In [ ]:
cryprcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
cryprcfg.model_path = f'/{colab_path}/models/rolling/crypto_0109'
cryprdf = run_model_nn(f'/{colab_path}/tickers/cryptotickers.csv', cfg=cryprcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/crypto_0109_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/crypto_0109_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/crypto_0109_close_model.pth'}

In [ ]:
cryprdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
6,DOGE-USD,0.11,2026-04-30,2026-05-28,0.09,0.11,0.09,-0.121212,-0.171420
10,BCH-USD,441.28,2026-04-30,2026-05-28,417.99,489.48,490.84,0.056253,0.041039
15,XLM-USD,0.16,2026-04-30,2026-05-28,0.15,0.19,0.17,0.062500,0.038273
5,DOT-USD,1.21,2026-04-30,2026-05-28,1.14,1.38,1.31,0.055096,0.036449
17,MATIC-USD,0.22,2025-03-24,2025-04-21,0.19,0.24,0.19,-0.060606,-0.034284
16,AAVE-USD,93.22,2026-04-30,2026-05-28,90.64,108.94,93.80,0.049060,0.028092
11,ICP-USD,2.39,2026-04-30,2026-05-28,2.28,2.75,2.47,0.046025,0.026226
7,FIL-USD,0.92,2026-04-30,2026-05-28,0.86,0.98,0.84,-0.028986,-0.012502
0,BTC-USD,76244.72,2026-04-30,2026-05-28,71759.88,89932.48,74857.14,0.034168,0.011213
12,AVAX-USD,9.10,2026-04-30,2026-05-28,8.80,10.37,8.85,0.026374,0.008687

In [ ]:
etftcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
etftcfg.model_path = f'/{colab_path}/models/transformer/etf_0112'
etftdf = run_model_nn(f'/{colab_path}/tickers/etftickers.csv', cfg=etftcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/etf_0112_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/etf_0112_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/etf_0112_close_model.pth'}

In [ ]:
etftdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
4,DXYZ,24.36,2026-03-20,2026-04-17,23.76,32.65,28.18,0.157499
9,IPOS,17.97,2026-03-20,2026-04-17,17.84,18.88,20.56,0.062512
19,SMH,384.74,2026-03-20,2026-04-17,355.84,399.67,327.85,-0.061392
14,IWO,309.55,2026-03-20,2026-04-17,280.17,321.37,281.84,-0.048748
30,XLK,135.29,2026-03-20,2026-04-17,123.68,141.20,121.64,-0.047675
23,VIS,311.14,2026-03-20,2026-04-17,309.53,335.62,332.47,0.047353
1,ARKK,69.15,2026-03-20,2026-04-17,68.60,76.81,71.43,0.045264
25,XLB,46.98,2026-03-20,2026-04-17,46.12,50.78,50.24,0.043990
35,XME,101.73,2026-03-20,2026-04-17,98.10,108.56,111.24,0.041646
11,IXN,101.08,2026-03-20,2026-04-17,89.26,106.09,95.90,-0.039540

In [ ]:
from google.colab import auth
import gspread
from oauth2client.client import GoogleCredentials
import pandas as pd
from google.auth import default


auth.authenticate_user()


creds, _ = default()
gc = gspread.authorize(creds)
# gc = gspread.authorize(GoogleCredentials.get_application_default())

In [ ]:
# Open your spreadsheet by name
spreadsheet = gc.open('Allocation')
# Or by URL: spreadsheet = gc.open_by_url('Your Spreadsheet URL')

# Select the worksheet (e.g., the first sheet)
worksheet = spreadsheet.worksheet("Buy")

# Get all values as a list of lists
data = worksheet.get_all_values()

# Convert to a Pandas DataFrame
sheetdf = pd.DataFrame(data[1:], columns=data[0]) # Assuming first row is header

In [ ]:
df = sheetdf[['Ticker']].copy()

# Apply the extraction function first, then filter based on the result
def extract_ticker(ticker_str):
    # Convert to string before splitting
    ticker_str = str(ticker_str)
    parts = ticker_str.split(':')
    if len(parts) > 1:
        return parts[1].strip() # Use strip to remove leading/trailing whitespace
    return ticker_str.strip() # Return the original string if no colon, also strip whitespace

df['Ticker'] = df['Ticker'].apply(extract_ticker)
# Tickers to remove
rmt = {"BTCUSD", "VXX"}
df = df[~df['Ticker'].isin(rmt)]
# Map of tickers to change to yf
tmap = {'BRK.B': 'BRK-B'}
df['Ticker'] = df['Ticker'].replace(tmap)
# Tickers to add
df = pd.concat([df, pd.DataFrame({'Ticker': ['BTC-USD', 'ETH-USD', 'ADA-USD', 'SOL-USD']})], ignore_index=True)
df.to_csv(f'/{colab_path}/tickers/stocktickers.csv', index=False)
df.to_csv(f'/{colab_path}/tickers/buystockstickers.csv', index=False)

In [ ]:
# Only have Tickers column

run_model_nn('buystocks', '0402', False, 500, 250, copy_tickers=False).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
333,QBTS,34.25,2025-10-08,2026-09-23,32.44,71.01,65.57,0.644964
96,CHGG,1.42,2025-10-08,2026-09-23,1.40,2.82,2.74,0.633803
97,SLP,16.47,2025-10-08,2026-09-23,16.09,32.07,31.69,0.616070
18,OUST,30.65,2025-10-08,2026-09-23,29.45,61.59,56.80,0.607830
9,HIMS,58.17,2025-10-08,2026-09-23,49.10,110.63,110.40,0.547934
252,LYFT,21.16,2025-10-08,2026-09-23,19.66,41.40,36.93,0.543636
6,DOMO,14.74,2025-10-08,2026-09-23,12.98,29.59,25.17,0.531886
326,ROOT,81.73,2025-10-08,2026-09-23,76.40,156.09,141.76,0.526367
122,LZ,9.97,2025-10-08,2026-09-23,9.63,19.32,16.65,0.524574
276,CRNC,11.96,2025-10-08,2026-09-23,11.62,21.43,21.43,0.518395

In [ ]:
 # !cp -ru results /content/drive/MyDrive/colab
 !rsync -av --ignore-existing results/* /content/drive/MyDrive/colab/results/
 ! find /content/drive/MyDrive/colab/ -type f -mtime +180 -delete -print

sending incremental file list
buystocks_0709_predictions.csv

sent 18,897 bytes  received 35 bytes  37,864.00 bytes/sec
total size is 18,770  speedup is 0.99

In [ ]:

# update zip /tmp/stock_cache.zip from files in folder /tmp/stock_cache
!zip -r /tmp/stock_cache.zip /tmp/stock_cache
!cp /tmp/stock_cache.zip /content/drive/MyDrive/colab/

In [ ]:
# Copy zip file from /content/drive/MyDrive/colab/ to /tmp/stock_cache.zip
!cp /content/drive/MyDrive/colab/stock_cache.zip /tmp/stock_cache.zip
!unzip  /tmp/stock_cache.zip