In [ ]:
pip install -q yahoo_fin > /dev/null

In [ ]:
pip install --upgrade yfinance > /dev/null

In [3]:
mkdir -p data results log

In [4]:
from google.colab import drive
drive.mount('/content/drive')
# ! find /content/drive/MyDrive/colab/ -type f -mtime +180 -delete -print

Mounted at /content/drive

In [5]:
import numpy as np
import pandas as pd

In [6]:
def show_prediction(name, suffix):
  df = pd.read_csv(f'results/{name}_{suffix}_predictions.csv')
  df['predicted_return'] = ((df['predicted_max']+df['predicted_min']+df['predicted_close'])/3 - df['current_price'])/df['current_price']
  return df.sort_values('predicted_return', ascending=False, key=abs)

In [7]:
def run_command_with_check(command):
  """Runs a command, prints stderr, and raises an exception if it fails."""
  process = subprocess.run(command, shell=True, capture_output=True, text=True, check=False)

  if process.returncode != 0:
    print("stderr:", process.stderr)  # Print stderr only on error
    raise subprocess.CalledProcessError(process.returncode, process.args, output=process.stdout, stderr=process.stderr)
  else:
    # Print or process stdout if needed
    #print("stdout:", process.stdout)
    pass

  return process.returncode

In [8]:
import os
import subprocess
def run_model_nn_cmd(prefix, version, do_train=False, window_size=None, future_days=None, hourly=False, copy_tickers=True):
    # copy drive/MyDrive/colab/results/nnreturn.py to local folder
    tickers = f"{prefix}tickers.csv"
    run_command_with_check(f"cp  /content/drive/MyDrive/colab/nnreturn.py .")
    if copy_tickers:
      run_command_with_check(f"cp  /content/drive/MyDrive/colab/tickers/{tickers} .")
    if not do_train:
      run_command_with_check(f"cp  /content/drive/MyDrive/colab/models/{prefix}_{version}_*.pth .")
      # Run nnreturn.py in results folder and throw exception if error
      today = pd.to_datetime('today').strftime('%m%d')
      run_command_with_check(f"rename 's/{version}/{today}/' *.pth")
      cmd_arg = ""
      if window_size:
        cmd_arg += f" --window-size {window_size}"
      if future_days:
        cmd_arg += f" --future-days {future_days}"
      if hourly:
        cmd_arg += " --hourly"
      run_command_with_check(f"python3 nnreturn.py --tickers-file {prefix}tickers.csv --mode analyze {cmd_arg}")
      run_command_with_check(f"cp {prefix}*predictions.csv results")
      # Get today's date

      return show_prediction(prefix, today)
    else:
      raise Exception("Not implemented")

In [ ]:
run_model_nn_cmd('etf', '0730').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
47,XLRE,41.43,2026-04-02,2026-04-30,36.52,42.07,36.99,-0.070078
34,VNQ,89.72,2026-04-02,2026-04-30,80.22,91.08,82.28,-0.057884
53,XOP,177.25,2026-04-02,2026-04-30,158.57,179.76,164.20,-0.054951
29,SMOG,138.66,2026-04-02,2026-04-30,126.34,140.72,130.10,-0.045243
14,IPO,42.12,2026-04-02,2026-04-30,42.03,44.21,45.03,0.038857
7,DXYZ,28.23,2026-04-02,2026-04-30,27.18,31.14,29.60,0.038139
46,XLP,81.65,2026-04-02,2026-04-30,74.71,82.62,78.84,-0.035844
54,XSW,143.99,2026-04-02,2026-04-30,129.66,148.52,140.56,-0.030627
4,DAPP,14.86,2026-04-02,2026-04-30,14.22,15.65,13.37,-0.030058
21,JETS,24.80,2026-04-02,2026-04-30,23.19,25.34,23.67,-0.029570

In [ ]:
# 0716 is hourly 20
run_model_nn('idx', '0716', window_size=20, future_days=8, hourly=True).head(10)

In [ ]:
import runml.pipeline
from runml import pipeline,findata
#from importlib import reload
# reload(runml.pipeline)

In [ ]:
# Skip some days from consecutive window to lessen test /train overlap
# findata.G_NON_OVERLAP= 0

Run following if like to save results in drive

In [ ]:
import numpy as np
# profit factor 2 = 50% of predicted gain due to early profit taking
def addAlloc(df, stop_loss, profit_factor=2):
  df['Alloc'] = df['Accu']/stop_loss - (1-df['Accu'])*profit_factor/abs(df['Gain'])
  df['Alloc'] = np.where(df['Alloc'] < 0, 0, df['Alloc'])
  return df

# profit factor 2 = 50% of predicted gain due to early profit taking
def addAllocHL(df, stop_loss, profit_factor=1):
    # Simplify following using apply
    def calculate_alloc(row):
        gain_low = min(row['Gain_l'], 0)
        gain_high = max(row['Gain_h'], 0)
        gain = min(row['Gain'], gain_high)
        average_gain = (gain_low+gain_high + 2*gain)/4
        if (average_gain == 0):
          return 0
        avg_accuracy = (row['Accu']+row['Accu_l']+row['Accu_h'])/3
        alloc =  avg_accuracy/stop_loss - (1-avg_accuracy)*profit_factor/abs(average_gain)
        return round(max(alloc, 0), 2)
    df['Alloc'] = df.apply(calculate_alloc, axis=1)
    return df

pd.options.display.max_columns = None

In [ ]:
import os
# findata.EPOCHS=200
def run_model(prefix, version, tickers, do_train):
  if (not do_train):
    os.system(f"cp  /content/drive/MyDrive/colab/results/{prefix}-{version}-* ./results/")
  mod = pipeline.RateReturnOnly(
    pipeline.FeatureSeq([pipeline.AddDayMonth(), pipeline.AddVWap(),
                         pipeline.AddMA(200), pipeline.Adj()]))
  df= pipeline.runModelCombinedVola(tickers, f"{prefix}-{version}", mod, do_train)
  # Save datafrme to prefix-version-prediction.csv
  df.to_csv(f"results/{prefix}-{version}-prediction.csv")
  return df

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
findata.G_SCALER = 'minmax' # Change to minmax
tickers = ['ABNB', 'ACLS' ,'AI', 'AMBA', 'APP',
           'BASE', 'BILL', 'BMBL', 'BYRN', 'CELH', 'CFLT', 'COHR', 'CRWD', 'CVNA',
           'DASH', 'DBX', 'DDOG', 'DOCN', 'DOCS', 'DOCU', 'DT', 'DXCM',
           'ELF', 'ENPH', 'ESTC', 'ETSY', 'EXPE', 'FIVE', 'FOUR',
           'GFS', 'GTLB', 'GLBE', 'HCP', 'HIMS', 'HOOD', 'HUBS',
           'INMD', 'INTA', 'IOT', 'IRDM', 'JAKK', 'JKS', 'KD', 'LYFT',
           'MBLY', 'MDB',  'MNDY', 'MNST', 'MPWR', 'MRVL', 'MXL','MTCH', 'MU',
           'NET', 'NVCR', 'NTNX', 'OKTA', 'OLED',
           'PAR', 'PANW',  'PAYX', 'PD', 'PI', 'PINS',
           'RBLX', 'RKLB', 'RMBS', 'RUM', 'SMCI', 'SMAR', 'SNAP', 'SNOW', 'SQ', 'SPOT',
           'SOUN', 'TEM', 'TEAM', 'TDOC', 'TMDX', 'TNDM', 'TOST', 'TRIP', 'TTD', 'TWLO',
           'U','UI', 'UBER', 'UPWK', 'WOLF', 'VEEV', 'Z', 'ZM', 'ZS']
df = run_model('ipos', '2a', tickers, True)

In [ ]:
addAllocHL(df, 0.10, 1)
df[(df.Gain>0)].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.EPOCHS=200
findata.G_SCALER = 'standard'
# https://seekingalpha.com/etfs-and-funds/etf-tables/sectors
tickers1 = ['ARKF', 'ARKK', 'ARKW', 'CIBR', 'DAPP', 'DIA', 'DTEC', 'DXYZ',
            'EEM', 'FDN', 'FPX',
            'ICLN', 'IGV', 'IJK', 'IJR', 'IPO',
            'IXC', 'IXN', 'IXP', 'IWM', 'IWO', 'IYZ',
            'JETS', 'JXI', 'MGK', 'MGV', 'MTUM',
            'ONLN', 'QQQ', 'SMH', 'SMOG', 'SPY', 'TDIV',
            'URA', 'VNQ', 'VT', 'VTI', 'VUG', 'WDIV', 'XITK',
            'XLB', 'XLC', 'XLE', 'XLF', 'XLI', 'XLK', 'XLP',
            'XLRE', 'XLU', 'XLV', 'XLY', 'XME', 'XNTK', 'XSW' ]
df1 = run_model('etf', '1b', tickers1, True)

In [ ]:
detail = res['ARKK'].final_df

mindate = detail['date'].min()
totalday = (detail['date'].max()-mindate).days
detail['diff'] = ((detail['date']-mindate).dt.days+1)/totalday
detail['sum_profit'] = (detail['buy_profit'] + detail['sell_profit'])/detail['adjclose']
detail['predicted_profit'] = ((detail['adjclose_15']-detail['adjclose'])/detail['adjclose']).abs()
profit_df = detail[detail['sum_profit'] > 0][['sum_profit', 'predicted_profit']]
average_profit = (profit_df['sum_profit']).mean()
excess_profit = (profit_df['sum_profit'] - profit_df['predicted_profit']).mean()
average_loss = -detail[detail['sum_profit'] < 0]['sum_profit'].mean()
detail['has_profit'] = np.where(detail['sum_profit'] > 0, 1 , 0)

accuracy = detail['has_profit'].mean()
weight_accuracy = (detail['has_profit']*detail['diff']).sum()/detail['diff'].sum()
(accuracy, weight_accuracy, average_profit, excess_profit, average_loss)

In [ ]:
addAlloc(df1, 0.10, 1)
df1.sort_values('Alloc', ascending=False)

In [ ]:
df1.to_csv('results/etf_12b_predictions.csv')

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
findata.G_SCALER = 'minmax'
tickers3 = [ 'AIRI', 'ALSMY', 'AMSC', 'AMSSY', 'ACHR',
            'APPS',  'AUR',  'ATOM', 'AWRE', 'AXTI',
            'BKKT', 'BGSF', 'BLDE', 'BLNK',
            'CARS', 'CHGG', 'CLOV', 'CRCT', 'CXM',
            'DLO', 'DM', 'EVGO', 'FSLY',
            'GOGO', 'GRAB', 'GRPN', 'GTE', 'HIMX', 'HIVE',
            'INDI', 'INLX',  'INVZ', 'JOBY',  'KIND',
            'LAZR', 'LFMD', 'LUMN', 'MAX', 'MITK', 'MTTR', 'MYTE',
            'NEPH', 'NNOX', 'OMQS', 'ONDS', 'OPEN', 'OTLY', 'OUST',
            'PAYO', 'PGY', 'PLUG', 'PTON', 'PUBM',
            'REAL', 'REI', 'RIG', 'RVYL',
            'SABR', 'SFIX', 'SLDP', 'SLE', 'SMWB', 'SST', 'STEM',
            'TDW', 'TDOC', 'TRUP', 'VTEX', 'VSAT', 'YEXT']
df3 = run_model('vols', '12b', tickers3, False)

In [ ]:
# df3.sort_values('Gain', ascending=False)
addAlloc(df3, 0.17, 1)
df3[(df3.Gain>0)].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.EPOCHS=200
tickers4 = ['AAPL', 'ACN', 'ADBE', 'AMD', 'AMZN', 'AVGO', 'BA', 'BKNG', 'BRK-B',
            'CAT', 'CDNS', 'CRM', 'COST', 'CSCO', 'DE', 'DELL', 'DHR', 'DIS',
            'GOOGL', 'FDX', 'HD', 'INTC', 'IBM', 'ISRG', 'KO', 'LLY',
            'META', 'MMC', 'MSFT', 'NKE', 'NVDA', 'NOW',
            'ORCL', 'PYPL', 'QCOM', 'SBUX',
            'TMO', 'TSLA', 'TXN', 'UNH', 'UPS', 'WMT']
df4 = run_model('mcap', '1b', tickers4, True)

In [ ]:
# df4.sort_values('Gain', ascending=False)
addAlloc(df4, 0.14, 1)
df4.sort_values('Alloc', ascending=False)

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
tickers5 = ['ASML', 'ADDDF', 'ADYEY',
            'BAK', 'BASFY', 'BESIY',
            'CAAP', 'CDUAF', 'COTY', 'COVTY', 'CDMGF', 'CX', 'DBOEY', 'DNNGY',
            'EADSF', 'EIFZF', 'EDNMF', 'ENGGY',
            'EQNR', 'ERIC', 'ERJ','ESEA', 'EVKIY',
            'FANUY', 'FDRVF', 'FQVLF', 'GLCNF',  'GLOB', 'HCMLY', 'HDELY',
            'HENKY', 'HYMTF', 'HMC', 'KNNGF', 'MELI', 'MGA',
            'RACE', 'LIN', 'LYB', 'LVMUY',
            'NHYDY', 'NOK', 'NU', 'NVO', 'NXPI',
            'ONON', 'OTGLY', 'PAX', 'POAHF', 'PROSF',
            'RNMBF', 'RYCEF', 'SAFRF', 'SFTBY',
            'SAP', 'SE', 'SIEGY', 'STLA',
            'TEF', 'TELNF', 'TGLS','THQQF', 'TKAMY', 'TRYIY', 'TSM',
            'VALE', 'VNT', 'YARIY', 'ZURVY']

df5 = run_model('gstock', '2a', tickers5, False)

In [ ]:
addAllocHL(df5, 0.14)
df5[df5.Gain > 0].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.G_SCALER = 'standard'
tickers6 = ['ARGT', 'EWD', 'FLN',
           'ECH', 'EPHE', 'EWA', 'EWG', 'EWI', 'EWJ',
           'EWC', 'EWM', 'EWP', 'EWT', 'EWW', 'EWY', 'EWZ',
           'IDX', 'ILF', 'INDA', 'KEMQ', 'KWT', 'THD', 'TUR', 'VNM', 'XCEM']
df6 = run_model('etf', '12a', tickers6, False)

In [ ]:
addAllocHL(df6, 0.07, 1)
df6.sort_values('Alloc', ascending=False)

In [ ]:
findata.EPOCHS=200
pipeline.IS_VERBOSE = False
findata.G_SCALER = 'standard'
tickers7 = ['AAL', 'ADI', 'ALB', 'AMR','ANF', 'APO', 'AQN', 'ARCH', 'ARE', 'ASC',
            'BAH', 'BAX', 'BKR', 'BLK', 'BX', 'BXC',
            'CBT', 'CC', 'CCI', 'CCJ', 'CF', 'CI', 'CIVI', 'CTAS',
            'CG',  'CLS', 'CMI', 'COKE', 'COP', 'CSL',
            'DAL', 'DD', 'DINO', 'DVN', 'DXC', 'EMN',
            'F', 'FCX', 'FICO', 'FIS', 'FLO', 'FMS', 'FSLR', 'GLW', 'GWW',
            'HIW', 'HSII', 'HPE', 'IFF', 'IP', 'IPI', 'IVZ',
            'KD', 'KHC', 'KMB', 'KVUE',
            'MMM', 'MOD', 'MPC', 'NFG', 'NTR', 'OMC', 'OLN', 'OSK',
            'PARA', 'PCAR', 'PEP', 'PETS', 'PNR', 'POR', 'POWL', 'PSTL',
            'RCL', 'RH', 'ROP',
            'SAFE', 'SBLK', 'SCCO', 'SPTN', 'SPG', 'SRE', 'STLD', 'STRL', 'SWK',
            'T', 'TEX', 'TGT', 'TDG', 'TMUS','TWI', 'UAL', 'URI',
            'VRTX', 'VZ', 'WDC', 'WHR', 'WSM', 'XOM', 'YORW', 'ZTS']
df7 = run_model('val', '1a', tickers7, False)

In [13]:
dfp = run_model_nn_cmd('pennystock', '1226')

In [14]:
dfp[dfp['predicted_return'] > 0].head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
6,ATOM,5.38,2026-04-17,2026-05-15,4.82,8.97,7.15,0.297398
66,BULL,6.66,2026-04-17,2026-05-15,6.26,10.10,7.29,0.183684
50,RVYL,6.40,2026-04-17,2026-05-15,5.92,9.22,7.19,0.163021
15,CXM,5.40,2026-04-17,2026-05-15,5.22,7.15,6.47,0.162963
87,QS,7.07,2026-04-17,2026-05-15,6.69,10.11,7.71,0.155587
12,CHGG,1.03,2026-04-17,2026-05-15,1.01,1.38,1.18,0.155340
56,SST,2.12,2026-04-17,2026-05-15,2.03,2.98,2.32,0.152516
44,PGY,15.23,2026-04-17,2026-05-15,12.99,22.93,16.48,0.146859
77,ZMDTF,0.73,2026-04-17,2026-05-15,0.67,0.97,0.87,0.146119
80,GTM,6.26,2026-04-17,2026-05-15,5.71,8.59,7.17,0.143237

In [ ]:
addAllocHL(df7, 0.10, 1)
df7[df7.Gain > 0].sort_values('Alloc', ascending=False).head(50)

In [ ]:
findata.EPOCHS=200
tickers8 = [ 'DBC', 'FXB', 'FXE', 'FXF', 'FXY',
            'GLD', 'ISHG', 'PDBC', 'SLV', 'SOYB',
            'TIP', 'TLT', 'USO', 'UUP', 'VTIP', 'WEAT']

df8 =  run_model('com', '12a', tickers8, True)

In [ ]:
addAllocHL(df8, 0.10, 1)
df8.sort_values('Alloc', ascending=False)

In [ ]:
run_model_nn_cmd('bluechipstock', '0221').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
2,ADBE,234.84,2026-03-27,2026-04-24,234.58,262.26,263.10,0.078663
1,ACN,192.60,2026-03-27,2026-04-24,189.78,215.87,204.30,0.055642
18,DIS,92.42,2026-03-27,2026-04-24,91.76,98.06,102.57,0.054570
32,ORCL,139.66,2026-03-27,2026-04-24,137.45,152.97,149.94,0.051029
31,NOW,99.41,2026-03-27,2026-04-24,98.31,109.55,103.72,0.044764
33,PYPL,43.59,2026-03-27,2026-04-24,42.35,48.25,45.84,0.043359
14,CSCO,79.92,2026-03-27,2026-04-24,72.95,79.32,78.01,-0.039540
12,CRM,179.31,2026-03-27,2026-04-24,175.29,196.02,187.46,0.038741
9,BRK-B,468.49,2026-03-27,2026-04-24,459.60,500.69,496.38,0.036429
0,AAPL,248.80,2026-03-27,2026-04-24,237.28,268.17,265.80,0.033293

In [ ]:
findata.EPOCHS=200
findata.G_SCALER = 'standard'
tickers9 = [ 'ADA-USD', 'AVAX-USD', 'BTC-USD', 'BCH-USD', 'DOGE-USD', 'DOT-USD',
            'ETH-USD', 'FIL-USD', 'ICP-USD', 'LINK-USD', 'LTC-USD',
            'MATIC-USD', 'NEAR-USD', 'SOL-USD', 'TON-USD', 'TRX-USD', 'XRP-USD']
df9 = run_model('cry', '11b', tickers9, False)

In [ ]:
addAllocHL(df9, 0.14, 1)
df9.sort_values('Alloc', ascending=False)

In [ ]:
run_model_nn_cmd('country', '1112').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
15,EWZ,39.54,2026-04-08,2026-05-06,38.27,42.15,41.39,0.026893
20,KWT,37.49,2026-04-08,2026-05-06,36.91,39.00,39.08,0.022406
23,VNM,18.33,2026-04-08,2026-05-06,17.49,18.53,17.80,-0.021277
18,INDA,49.28,2026-04-08,2026-05-06,47.61,51.49,50.93,0.014813
14,EWY,139.33,2026-04-08,2026-05-06,135.64,149.28,138.70,0.013469
11,EWP,57.13,2026-04-08,2026-05-06,53.41,58.94,57.06,-0.011553
0,ARGT,94.35,2026-04-08,2026-05-06,92.21,98.25,95.38,0.009857
24,XCEM,43.83,2026-04-08,2026-05-06,41.71,44.87,43.75,-0.008822
5,EWA,29.44,2026-04-08,2026-05-06,28.26,30.41,28.92,-0.008265
19,KEMQ,23.48,2026-04-08,2026-05-06,23.05,24.78,23.16,0.007808

In [ ]:
run_model_nn_cmd('global', '1107').head(15)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
44,KLAR,13.17,2026-04-06,2026-05-04,12.60,15.55,15.75,0.111111
66,RACE,338.28,2026-04-06,2026-05-04,321.59,413.05,370.84,0.089315
59,ONON,33.67,2026-04-06,2026-05-04,33.01,40.66,35.68,0.082566
64,POAHF,38.00,2026-04-06,2026-05-04,36.30,43.95,42.74,0.078860
65,PROSF,45.00,2026-04-06,2026-05-04,42.38,52.77,48.88,0.066889
32,ESEA,67.69,2026-04-06,2026-05-04,59.43,68.34,62.35,-0.063771
1,ADYEY,9.80,2026-04-06,2026-05-04,8.40,9.86,9.43,-0.058163
18,CRTO,18.65,2026-04-06,2026-05-04,16.44,21.28,21.40,0.056658
3,ALSMY,2.78,2026-04-06,2026-05-04,2.70,3.17,2.93,0.055156
85,VALE,16.14,2026-04-06,2026-05-04,15.68,18.60,16.78,0.054523
41,HMC,23.84,2026-04-06,2026-05-04,22.89,26.55,25.79,0.051874
76,SIFY,13.48,2026-04-06,2026-05-04,11.32,14.12,12.91,-0.051682
54,NOK,8.89,2026-04-06,2026-05-04,7.77,9.05,8.51,-0.050244
7,AUNA,5.84,2026-04-06,2026-05-04,5.41,6.66,6.32,0.049658
49,LYB,78.62,2026-04-06,2026-05-04,67.35,83.49,73.50,-0.048843

In [ ]:
run_model_nn_cmd('valuestock', '0301').head(15)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
82,MPX,7.42,2026-04-08,2026-05-06,7.55,8.93,7.93,0.096586
24,CCJ,115.89,2026-04-08,2026-05-06,116.60,138.41,122.95,0.087123
123,UAL,96.30,2026-04-08,2026-05-06,91.56,113.68,106.06,0.077535
0,AAL,11.41,2026-04-08,2026-05-06,11.07,13.10,12.65,0.075665
31,CNC,37.27,2026-04-08,2026-05-06,35.79,43.02,41.07,0.072176
116,TDG,1220.20,2026-04-08,2026-05-06,1189.16,1324.47,1410.07,0.071873
4,ALB,177.30,2026-04-08,2026-05-06,156.72,182.40,154.97,-0.071085
99,REPX,39.20,2026-04-08,2026-05-06,35.48,39.22,34.84,-0.068537
85,NTR,74.90,2026-04-08,2026-05-06,67.03,76.31,66.35,-0.066800
74,LULU,158.86,2026-04-08,2026-05-06,156.67,176.70,175.02,0.066746
100,RH,120.10,2026-04-08,2026-05-06,113.07,137.33,131.46,0.059839
69,KD,13.00,2026-04-08,2026-05-06,12.34,15.12,13.86,0.059487
66,IP,37.06,2026-04-08,2026-05-06,34.84,41.69,40.98,0.056935
107,SKYW,95.15,2026-04-08,2026-05-06,90.06,108.17,102.99,0.055246
129,VTR,84.05,2026-04-08,2026-05-06,76.71,86.17,75.40,-0.055007

In [ ]:
run_model_nn_cmd('commodity', '0312').head(5)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
9,SOYB,24.36,2026-04-08,2026-05-06,23.81,27.89,24.75,0.046114
4,FXY,57.90,2026-04-08,2026-05-06,56.55,60.31,58.58,0.010017
13,UUP,27.53,2026-04-08,2026-05-06,26.79,28.25,27.28,-0.003269
5,GLD,434.53,2026-04-08,2026-05-06,422.95,445.13,431.30,-0.003230
8,SLV,67.47,2026-04-08,2026-05-06,65.62,69.14,67.14,-0.002520

In [ ]:
run_model_nn_cmd('crypto', '0214').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
6,DOGE-USD,0.09,2026-02-23,2026-03-23,0.09,0.10,0.13,0.185185
17,ATOM-USD,2.14,2026-02-23,2026-03-23,2.19,2.83,2.26,0.133956
8,LTC-USD,51.92,2026-02-23,2026-03-23,51.99,58.28,63.79,0.117488
12,AVAX-USD,8.53,2026-02-23,2026-03-23,7.54,8.79,12.07,0.109809
5,DOT-USD,1.28,2026-02-23,2026-03-23,1.26,1.52,1.45,0.101563
3,ADA-USD,0.27,2026-02-23,2026-03-23,0.26,0.29,0.34,0.098765
4,XRP-USD,1.37,2026-02-23,2026-03-23,1.37,1.49,1.63,0.092457
7,FIL-USD,0.89,2026-02-23,2026-03-23,0.87,0.99,1.04,0.086142
2,SOL-USD,79.16,2026-02-23,2026-03-23,81.26,91.46,84.47,0.082996
13,LINK-USD,8.38,2026-02-23,2026-03-23,8.14,9.50,9.46,0.077963

In [ ]:
df = run_model_nn_cmd('techstock', '0312')
df.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
82,RDDT,135.98,2026-04-02,2026-04-30,106.39,132.47,118.70,-0.123499
93,TDOC,5.23,2026-04-02,2026-04-30,5.06,6.23,6.20,0.114723
101,TTWO,199.85,2026-04-02,2026-04-30,188.41,271.24,207.97,0.113535
9,ASTS,89.00,2026-04-02,2026-04-30,77.32,88.59,75.78,-0.094794
71,OKTA,80.21,2026-04-02,2026-04-30,78.92,96.94,87.48,0.094377
69,NVCR,10.55,2026-04-02,2026-04-30,9.51,10.72,8.54,-0.090995
30,DT,37.30,2026-04-02,2026-04-30,37.11,44.54,40.05,0.087578
74,PANW,161.59,2026-04-02,2026-04-30,133.59,170.12,139.59,-0.085546
72,OLED,88.44,2026-04-02,2026-04-30,86.21,103.79,96.85,0.081147
94,TEAM,68.14,2026-04-02,2026-04-30,65.40,80.54,74.64,0.079053

In [ ]:
stdf = run_model_nn_cmd('stock', '0227', window_size=40)
# stdf[stdf['predicted_return']>0].head(20)
stdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
386,SOL-USD,83.77,2026-03-28,2026-04-25,81.02,114.05,116.56,0.240022
385,ADA-USD,0.25,2026-03-28,2026-04-25,0.22,0.38,0.31,0.213333
8,HIMS,19.38,2026-03-27,2026-04-24,17.99,27.45,25.08,0.212934
24,MBLY,6.73,2026-03-27,2026-04-24,6.34,9.02,8.09,0.161466
378,QUBT,6.66,2026-03-27,2026-04-24,6.32,8.78,8.07,0.159660
369,SQNS,2.54,2026-03-27,2026-04-24,2.35,3.41,3.06,0.157480
360,BULL,4.82,2026-03-27,2026-04-24,4.60,6.49,5.50,0.147303
250,ENVX,5.23,2026-03-27,2026-04-24,5.00,6.37,6.45,0.135755
382,EWY,120.98,2026-03-27,2026-04-24,114.12,158.69,135.96,0.126274
332,OKLO,50.23,2026-03-27,2026-04-24,46.26,62.06,61.15,0.124627
266,GDDY,79.97,2026-03-27,2026-04-24,75.56,99.62,93.51,0.119962
161,NOW,99.41,2026-03-27,2026-04-24,91.31,128.61,112.83,0.115750
30,AI,7.76,2026-03-27,2026-04-24,7.33,9.32,9.29,0.114261
262,LUNR,17.52,2026-03-27,2026-04-24,13.91,18.53,14.15,-0.113584
198,MSTR,126.03,2026-03-27,2026-04-24,119.02,160.95,140.99,0.113386
163,INTC,43.13,2026-03-27,2026-04-24,40.71,55.40,47.93,0.113224
372,FIX,1366.77,2026-03-27,2026-04-24,1291.49,1784.40,1450.52,0.103919
273,QTWO,45.42,2026-03-27,2026-04-24,42.84,61.06,46.49,0.103699
303,FOUR,44.48,2026-03-27,2026-04-24,42.80,50.72,53.59,0.102443
259,BYRN,8.80,2026-03-27,2026-04-24,7.87,11.17,9.98,0.099242

In [ ]:
run_model_nn_cmd('buystocks', '0402', False, 500, 250).head(20)
# show_prediction('buystocks', '0508').head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
321,AEVA,15.65,2026-03-18,2027-03-03,15.49,31.05,29.89,0.627902
155,INDI,2.61,2026-03-18,2027-03-03,2.63,5.03,4.75,0.584930
355,BITF,2.29,2026-03-18,2027-03-03,2.26,4.37,4.21,0.577875
46,EL,88.15,2026-03-18,2027-03-03,88.84,160.72,164.61,0.566156
228,SLDP,3.13,2026-03-18,2027-03-03,2.65,6.05,5.84,0.548456
148,FIVE,214.07,2026-03-18,2027-03-03,217.66,411.60,363.97,0.546581
93,CHGG,0.58,2026-03-18,2027-03-03,0.55,1.08,1.06,0.545977
324,ENPH,43.53,2026-03-18,2027-03-03,42.38,87.05,71.55,0.539015
194,TGT,115.63,2026-03-18,2027-03-03,112.32,215.84,203.21,0.531811
25,INSG,12.84,2026-03-18,2027-03-03,11.15,23.37,23.99,0.518951
337,WULF,15.53,2026-03-18,2027-03-03,14.48,30.49,25.51,0.512771
342,OPEN,5.36,2026-03-18,2027-03-03,4.65,10.41,9.22,0.509950
34,UP,0.58,2026-03-18,2027-03-03,0.50,1.14,0.97,0.500000
326,PFE,27.33,2026-03-18,2027-03-03,26.13,53.27,43.22,0.495548
76,ETSY,54.72,2026-03-18,2027-03-03,53.47,104.50,86.47,0.489035
80,SKYT,27.62,2026-03-18,2027-03-03,27.71,52.20,42.89,0.482018
276,RVLV,23.21,2026-03-18,2027-03-03,22.06,45.03,35.75,0.476950
48,DOCU,48.09,2026-03-18,2027-03-03,43.27,94.13,74.83,0.471061
240,LYFT,13.69,2026-03-18,2027-03-03,12.58,22.18,25.64,0.470660
327,PATH,12.37,2026-03-18,2027-03-03,11.97,21.64,20.77,0.465373

In [ ]:
run_model_nn_cmd('techstock', '0224', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
76,RBLX,67.09,2026-02-24,2027-02-09,60.44,129.31,119.58,0.536891
98,UI,758.69,2026-02-24,2027-02-09,674.71,1480.07,1333.45,0.532567
77,RMBS,98.57,2026-02-24,2027-02-09,77.40,187.03,159.78,0.434547
85,SYNA,81.06,2026-02-24,2027-02-09,72.87,156.04,114.11,0.410560
42,HOOD,73.39,2026-02-24,2027-02-09,53.04,143.05,113.82,0.407594
96,U,18.29,2026-02-24,2027-02-09,13.21,33.19,30.43,0.400219
51,LYFT,13.53,2026-02-24,2027-02-09,10.40,24.61,21.32,0.387780
102,XYZ,51.00,2026-02-24,2027-02-09,46.32,89.32,76.53,0.386732
61,NET,163.81,2026-02-24,2027-02-09,117.50,297.29,258.36,0.369778
95,TWLO,113.85,2026-02-24,2027-02-09,94.80,213.00,156.70,0.359977

In [ ]:
run_model_nn_cmd('etf', '0225', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
2,ARKW,127.36,2026-02-25,2027-02-10,104.27,233.10,213.17,0.440902
19,URA,55.91,2026-02-25,2027-02-10,45.55,111.66,84.43,0.440649
0,ARKF,39.11,2026-02-25,2027-02-10,31.04,67.24,57.83,0.330521
32,XME,120.68,2026-02-25,2027-02-10,95.07,206.56,167.50,0.295796
1,ARKK,73.94,2026-02-25,2027-02-10,60.91,115.11,106.08,0.271752
17,SMH,426.83,2026-02-25,2027-02-10,318.37,628.84,572.22,0.186600
10,IXP,120.99,2026-02-25,2027-02-10,105.64,155.11,153.09,0.140149
31,XLY,116.86,2026-02-25,2027-02-10,107.39,143.45,144.19,0.126790
23,XLC,116.18,2026-02-25,2027-02-10,100.89,147.56,141.63,0.119183
27,XLK,143.10,2026-02-25,2027-02-10,112.55,192.00,173.66,0.113930

In [ ]:
run_model_nn_cmd('bluechipstock', '0117', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
5,AVGO,328.46,2026-01-29,2027-01-14,287.62,608.10,568.04,0.485478
32,ORCL,164.71,2026-01-29,2027-01-14,152.25,315.91,249.25,0.451865
21,INTC,48.06,2026-01-29,2027-01-14,43.10,83.98,73.79,0.393189
17,DIS,111.24,2026-01-29,2027-01-14,106.58,174.07,155.86,0.308013
6,BA,234.45,2026-01-29,2027-01-14,223.97,336.86,318.81,0.250643
22,IBM,304.70,2026-01-29,2027-01-14,292.43,439.38,406.63,0.245422
39,UNH,292.80,2026-01-29,2027-01-14,151.07,325.39,187.66,-0.243944
18,GOOGL,335.86,2026-01-29,2027-01-14,301.50,478.89,438.51,0.209730
13,CSCO,78.73,2026-01-29,2027-01-14,74.46,108.06,98.34,0.189127
30,NVDA,191.13,2026-01-29,2027-01-14,150.83,254.82,273.16,0.183854

In [ ]:
run_model_nn_cmd('pennystock', '0122', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
109,AUID,1.63,2026-02-12,2026-03-12,1.48,2.54,1.86,0.202454
12,CHGG,0.57,2026-02-12,2026-03-12,0.54,0.94,0.54,0.181287
15,CXM,5.39,2026-02-12,2026-03-12,5.23,7.00,6.33,0.147805
64,ALAR,7.22,2026-02-12,2026-03-12,4.98,8.15,5.66,-0.132502
108,MRAM,11.00,2026-02-12,2026-03-12,10.61,13.87,12.87,0.131818
66,IREN,41.04,2026-02-12,2026-03-12,29.70,42.13,35.42,-0.128899
85,WKEY,6.80,2026-02-12,2026-03-12,5.93,9.05,8.04,0.128431
38,ONDS,8.97,2026-02-12,2026-03-12,6.43,10.12,7.13,-0.120030
40,OTLY,11.08,2026-02-12,2026-03-12,9.92,13.37,13.91,0.119134
107,UDMY,4.51,2026-02-12,2026-03-12,4.32,5.82,4.93,0.113821

In [ ]:
run_model_nn_cmd('global', '0226', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
62,ASM,9.10,2026-02-26,2027-02-11,7.98,18.16,17.91,0.613553
43,RYCEF,18.50,2026-02-26,2027-02-11,17.42,36.29,35.73,0.611532
69,NVTS,9.51,2026-02-26,2027-02-11,7.57,18.56,17.82,0.540484
26,KNNGF,74.00,2026-02-25,2027-02-10,68.16,135.48,127.25,0.490495
47,SE,109.23,2026-02-26,2027-02-11,96.75,210.92,177.28,0.479905
61,SIFY,16.10,2026-02-26,2027-02-11,12.72,30.12,28.16,0.469979
45,SFTBY,13.05,2026-02-26,2027-02-11,9.14,24.40,23.71,0.462324
20,FQVLF,29.79,2026-02-26,2027-02-11,28.28,56.88,44.80,0.454179
3,BAK,3.73,2026-02-26,2027-02-11,3.60,6.33,5.94,0.418231
65,KEP,22.26,2026-02-26,2027-02-11,18.67,39.56,36.38,0.416742

In [ ]:
run_model_nn_cmd('country', '0310', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
14,EWY,134.80,2026-03-10,2027-02-23,120.57,209.94,185.97,0.277151
11,EWP,54.49,2026-03-10,2027-02-23,50.56,76.08,79.38,0.260292
13,EWW,75.26,2026-03-10,2027-02-23,68.85,102.68,99.91,0.202232
19,KEMQ,24.11,2026-03-10,2027-02-23,21.01,31.51,33.29,0.186368
17,ILF,35.08,2026-03-10,2027-02-23,31.69,47.79,44.85,0.181395
9,EWC,56.96,2026-03-10,2027-02-23,54.09,73.55,73.38,0.176381
15,EWZ,37.71,2026-03-10,2027-02-23,34.12,51.67,46.92,0.173075
2,FLN,25.80,2026-03-10,2027-02-23,23.60,34.91,32.26,0.172739
24,XCEM,42.65,2026-03-10,2027-02-23,38.80,56.34,53.48,0.161547
7,EWI,54.30,2026-03-10,2027-02-23,47.69,69.91,68.44,0.142050

In [ ]:
run_model_nn_cmd('valuestock', '0219', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
86,NUTX,99.59,2026-02-20,2027-02-05,81.31,186.03,192.93,0.540550
113,STRL,433.26,2026-02-20,2027-02-05,315.79,859.64,826.69,0.540353
80,MP,55.18,2026-02-20,2027-02-05,50.21,103.51,97.98,0.520478
24,CCJ,118.41,2026-02-20,2027-02-05,103.98,225.22,203.20,0.498747
96,POWL,539.63,2026-02-20,2027-02-05,431.36,968.34,894.65,0.417237
61,GLW,137.42,2026-02-20,2027-02-05,112.34,238.97,214.61,0.372726
130,WDC,290.10,2026-02-20,2027-02-05,178.91,478.56,493.51,0.322509
30,CLS,296.71,2026-02-20,2027-02-05,219.38,513.79,441.41,0.319560
87,OLN,23.90,2026-02-20,2027-02-05,22.58,37.70,33.63,0.309763
23,CCI,88.12,2026-02-20,2027-02-05,86.67,137.41,118.60,0.296263

In [ ]:
run_model_nn_cmd('crypto', '0223', False, 500, 250).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
16,AAVE-USD,114.99,2026-02-23,2027-02-08,42.99,154.25,48.05,-0.288953
17,MATIC-USD,0.22,2025-03-24,2026-03-09,0.17,0.41,0.26,0.272727
0,BTC-USD,64800.95,2026-02-23,2027-02-08,24188.92,82484.52,36648.62,-0.262757
3,ADA-USD,0.26,2026-02-23,2027-02-08,0.16,0.49,0.24,0.141026
13,LINK-USD,8.67,2026-02-22,2027-02-07,6.08,15.14,8.39,0.138408
7,FIL-USD,0.89,2026-02-23,2027-02-08,0.45,1.16,0.70,-0.134831
12,AVAX-USD,8.87,2026-02-22,2027-02-07,6.98,16.72,6.46,0.133408
6,DOGE-USD,0.09,2026-02-23,2027-02-08,0.05,0.13,0.06,-0.111111
8,LTC-USD,53.47,2026-02-22,2027-02-07,25.67,95.68,56.87,0.111028
5,DOT-USD,1.27,2026-02-23,2027-02-08,0.68,1.87,0.85,-0.107612

In [15]:
import sys
sys.path.append('/content')
# !ln -s drive/MyDrive/colab/stock_prediction /content/
import stock_prediction.stock_prediction.stock_predictor_lib
from stock_prediction.stock_prediction.stock_predictor_lib import run_model_nn, show_prediction, StockPredictorLib, Config
colab_path = 'content/drive/MyDrive/colab'

In [ ]:
techcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
colab_path = 'content/drive/MyDrive/colab'
techcfg.model_path = f'/{colab_path}/models/transformer/techstock_1220'
techdf = run_model_nn(f'/{colab_path}/tickers/techstocktickers.csv', cfg=techcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/techstock_1220_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/techstock_1220_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/techstock_1220_close_model.pth'}

In [ ]:
techdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
48,MU,375.85,2026-02-10,2026-03-10,227.85,382.23,223.76,-0.260485
44,MNDY,76.30,2026-02-10,2026-03-10,72.68,108.91,99.80,0.229314
11,COHR,230.74,2026-02-10,2026-03-10,172.44,237.92,138.73,-0.206770
63,RMBS,107.14,2026-02-10,2026-03-10,70.81,110.35,80.81,-0.184960
68,TEAM,96.41,2026-02-10,2026-03-10,92.85,126.74,122.82,0.183868
61,PUBM,6.84,2026-02-10,2026-03-10,6.75,9.32,8.00,0.173002
34,HUBS,239.07,2026-02-10,2026-03-10,215.79,318.56,304.50,0.169602
77,UI,717.46,2026-02-10,2026-03-10,486.38,727.43,588.56,-0.162615
49,NET,180.16,2026-02-10,2026-03-10,135.93,185.46,133.18,-0.158951
76,U,29.05,2026-02-10,2026-03-10,21.34,30.65,21.81,-0.153184

In [11]:
techrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
techrcfg.model_path = f'/{colab_path}/models/rolling/techstock_0109'
techrdf = run_model_nn(f'/{colab_path}/tickers/techstocktickers.csv', cfg=techrcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/techstock_0109_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/techstock_0109_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/techstock_0109_close_model.pth'}

In [12]:
techrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
12,BMBL,4.27,2026-04-17,2026-05-15,3.21,4.36,3.48,-0.137393,-0.164160
110,Z,46.83,2026-04-17,2026-05-15,35.86,48.20,40.49,-0.113460,-0.118442
88,SNAP,6.05,2026-04-17,2026-05-15,4.61,6.09,5.57,-0.103581,-0.105883
35,ESTC,47.42,2026-04-17,2026-05-15,45.57,53.34,55.60,0.086110,0.081852
58,MDB,263.24,2026-04-17,2026-05-15,192.53,272.05,250.07,-0.095059,-0.070946
15,CEG,295.61,2026-04-17,2026-05-15,247.26,302.64,273.21,-0.071851,-0.067457
85,S,13.94,2026-04-17,2026-05-15,11.13,14.66,12.71,-0.079388,-0.060852
28,DOCS,24.73,2026-04-17,2026-05-15,21.67,26.02,21.48,-0.067664,-0.053998
5,AMKR,68.43,2026-04-17,2026-05-15,58.98,72.69,59.40,-0.069268,-0.051573
37,EXPE,266.85,2026-04-17,2026-05-15,217.73,280.57,246.17,-0.070052,-0.050968

In [ ]:
defetfcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
defetfcfg.model_path = f'/{colab_path}/models/rolling/etf_1221'
etfdf = run_model_nn(f'/{colab_path}/tickers/etftickers.csv', cfg=defetfcfg)
etfdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/etf_1221_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/etf_1221_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/etf_1221_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
22,XLC,116.91,2026-01-27,2026-02-24,114.02,121.17,127.73,0.034756
21,XLB,49.99,2026-01-27,2026-02-24,48.59,53.51,52.07,0.028006
0,ARKF,46.05,2026-01-27,2026-02-24,45.11,49.12,47.49,0.025841
31,XME,128.38,2026-01-27,2026-02-24,125.85,138.44,128.85,0.020772
19,URA,57.85,2026-01-27,2026-02-24,56.05,63.46,57.59,0.020455
3,DIA,490.07,2026-01-27,2026-02-24,479.53,513.22,507.28,0.020283
28,XLU,43.41,2026-01-27,2026-02-24,40.92,44.09,42.89,-0.017891
16,QQQ,631.13,2026-01-27,2026-02-24,615.90,651.98,656.09,0.016151
8,IXC,46.34,2026-01-27,2026-02-24,45.23,48.58,47.37,0.015537
15,JXI,81.94,2026-01-27,2026-02-24,77.62,83.46,81.52,-0.013099

In [ ]:
tvolcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
tvolcfg.model_path = f'/{colab_path}/models/transformer/pennystock_1226'
tvoldf = run_model_nn(f'/{colab_path}/tickers/pennystocktickers.csv', cfg=tvolcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/pennystock_1226_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/pennystock_1226_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/pennystock_1226_close_model.pth'}

In [ ]:
tvoldf[tvoldf['predicted_return']> 0].head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
2,AMSSY,5.74,2026-02-24,2026-03-24,5.63,8.61,15.48,0.725900
54,SLE,3.49,2026-02-25,2026-03-25,3.42,6.82,3.86,0.346705
91,PETS,2.79,2026-02-25,2026-03-25,2.75,4.56,3.10,0.243728
89,GPRO,0.84,2026-02-25,2026-03-25,0.74,1.16,1.10,0.190476
109,AUID,1.50,2026-02-25,2026-03-25,1.25,1.96,2.12,0.184444
6,ATOM,5.74,2026-02-25,2026-03-25,4.16,8.66,7.40,0.174216
90,DNUT,2.99,2026-02-25,2026-03-25,2.80,3.95,3.22,0.111483
31,LFMD,2.69,2026-02-25,2026-03-25,2.61,3.49,2.81,0.104089
69,BNED,8.32,2026-02-25,2026-03-25,4.69,12.04,10.64,0.096554
28,INVZ,0.85,2026-02-25,2026-03-25,0.72,1.19,0.87,0.090196

In [ ]:
tvolrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
tvolrcfg.model_path = f'/{colab_path}/models/rolling/pennystock_0114'
tvolrdf = run_model_nn(f'/{colab_path}/tickers/pennystocktickers.csv', cfg=tvolrcfg)

In [ ]:
tvolrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
19,FSLY,25.20,2026-03-20,2026-04-17,19.92,41.69,34.39,0.269841
2,AMSSY,5.10,2026-03-20,2026-04-17,4.68,7.22,7.38,0.260131
8,AXTI,54.24,2026-03-20,2026-04-17,46.72,75.46,72.43,0.195981
75,TSSI,10.95,2026-03-20,2026-04-17,9.08,16.40,13.12,0.175038
79,ACFN,18.12,2026-03-20,2026-04-17,16.97,24.39,22.45,0.173841
81,AEHR,34.52,2026-03-20,2026-04-17,30.58,51.69,38.93,0.170336
37,NNOX,2.41,2026-03-20,2026-04-17,2.26,2.95,3.20,0.163209
74,TGEN,2.23,2026-03-20,2026-04-17,2.03,3.15,2.51,0.149477
92,GDRX,2.03,2026-03-20,2026-04-17,1.93,2.81,2.26,0.149425
10,BLNK,0.56,2026-03-20,2026-04-17,0.55,0.69,0.69,0.148810

In [ ]:
tbvolcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
tbvolcfg.model_path = f'/{colab_path}/models/transformer_base/pennystock_0417'
tbvoldf = run_model_nn(f'/{colab_path}/tickers/pennystocktickers.csv', cfg=tbvolcfg)

In [20]:
tbvoldf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
50,RVYL,6.41,2026-04-17,2026-05-15,5.05,6.77,5.90,-0.078523,-0.056285
73,EOSE,7.15,2026-04-17,2026-05-15,6.37,9.84,7.41,0.101166,0.050327
0,ALSMY,1.91,2026-04-17,2026-05-15,1.77,2.40,1.98,0.073298,0.039180
19,FSLY,24.45,2026-04-17,2026-05-15,18.18,28.42,21.29,-0.074438,-0.031605
70,FUBO,13.18,2026-04-17,2026-05-15,9.40,15.02,12.47,-0.067021,-0.025766
55,SMWB,2.62,2026-04-17,2026-05-15,2.34,3.37,2.65,0.063613,0.024573
17,EVGO,2.19,2026-04-17,2026-05-15,2.00,2.68,2.23,0.051750,0.020768
10,BLNK,0.70,2026-04-17,2026-05-15,0.57,0.76,0.67,-0.047619,-0.020454
101,GPUS,0.16,2026-04-17,2026-05-15,0.13,0.22,0.16,0.062500,0.016704
46,PTON,5.03,2026-04-17,2026-05-15,4.35,5.41,4.78,-0.036448,-0.015351

In [ ]:
bctcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
bctcfg.model_path = f'/{colab_path}/models/transformer/bluechipstock_0328'
bctdf = run_model_nn(f'/{colab_path}/tickers/bluechipstocktickers.csv', cfg=bctcfg)
bctdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/bluechipstock_0328_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/bluechipstock_0328_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/bluechipstock_0328_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
27,META,525.72,2026-03-27,2026-04-24,499.04,597.66,613.61,0.084424
34,PYPL,43.59,2026-03-27,2026-04-24,42.60,50.61,48.42,0.083047
37,TMO,473.36,2026-03-27,2026-04-24,461.29,537.60,534.63,0.079883
36,SBUX,86.81,2026-03-27,2026-04-24,83.54,98.71,96.34,0.069731
1,ACN,192.60,2026-03-27,2026-04-24,188.49,211.84,216.90,0.068242
8,BKNG,4062.14,2026-03-27,2026-04-24,4002.21,4724.27,4271.65,0.066608
26,LLY,878.24,2026-03-27,2026-04-24,847.94,985.07,960.48,0.060261
23,INTC,43.13,2026-03-27,2026-04-24,36.76,45.59,39.63,-0.057269
19,FDX,343.97,2026-03-27,2026-04-24,303.25,348.78,320.88,-0.057176
33,ORCL,139.66,2026-03-27,2026-04-24,137.70,148.83,154.53,0.052699

In [ ]:
bcrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
bcrcfg.model_path = f'/{colab_path}/models/rolling/bluechipstock_0117'
bcrdf = run_model_nn(f'/{colab_path}/tickers/bluechipstocktickers.csv', cfg=bcrcfg)
bcrdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/bluechipstock_0117_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/bluechipstock_0117_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/bluechipstock_0117_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
14,CSCO,78.43,2026-02-26,2026-03-26,71.19,80.25,69.55,-0.060776
25,KO,80.25,2026-02-26,2026-03-26,78.57,90.78,85.56,0.058816
15,DE,620.78,2026-02-26,2026-03-26,607.38,703.49,655.81,0.056026
8,BKNG,4268.91,2026-02-26,2026-03-26,3543.37,4446.64,4099.32,-0.056017
5,ANET,130.25,2026-02-26,2026-03-26,124.23,150.03,137.54,0.053871
23,IBM,244.44,2026-02-26,2026-03-26,227.92,267.40,274.73,0.050087
33,ORCL,148.46,2026-02-26,2026-03-26,138.79,166.40,159.95,0.044367
9,BRK-B,499.40,2026-02-26,2026-03-26,484.76,553.69,521.03,0.040902
7,BA,228.42,2026-02-26,2026-03-26,223.73,252.98,236.35,0.040569
39,TXN,213.21,2026-02-26,2026-03-26,205.29,232.98,226.08,0.038647

In [ ]:
buystkcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
buystkcfg.model_path = f'/{colab_path}/models/transformer/buystocks_0123'
buystkcfg.model.window_size = 500
buystkcfg.model.future_days = 250
buystkdf = run_model_nn(f'/{colab_path}/tickers/buystockstickers.csv', cfg=buystkcfg)

In [ ]:
buystkdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
270,CRNC,7.20,2026-04-02,2027-03-18,7.19,95.37,65.25,6.768981
93,CHGG,0.75,2026-04-02,2027-03-18,0.56,9.71,4.15,5.408889
17,INVZ,0.66,2026-04-02,2027-03-18,0.65,6.82,4.04,4.813131
85,RIVN,15.19,2026-04-02,2027-03-18,14.76,129.73,75.93,3.836954
9,SFIX,3.38,2026-04-02,2027-03-18,3.33,25.39,16.96,3.504931
16,OUST,19.58,2026-04-02,2027-03-18,12.29,109.03,98.20,2.737147
5,DOMO,2.87,2026-04-02,2027-03-18,2.63,10.95,15.60,2.389082
355,SQNS,2.41,2026-04-02,2027-03-18,2.30,14.28,5.22,2.015214
329,AEVA,13.44,2026-04-02,2027-03-18,10.04,48.77,62.08,1.998264
54,LCID,9.79,2026-04-02,2027-03-18,9.06,43.64,34.92,1.983316
34,UP,0.50,2026-04-02,2027-03-18,0.38,2.20,1.72,1.866667
351,OPEN,4.60,2026-04-02,2027-03-18,4.44,18.32,16.27,1.828261
27,BNED,8.89,2026-04-02,2027-03-18,8.12,10.49,56.17,1.803900
332,ENPH,36.46,2026-04-02,2027-03-18,36.19,81.20,164.00,1.572591
158,INDI,3.12,2026-04-02,2027-03-18,3.06,12.84,7.73,1.524573
218,FSLY,33.85,2026-04-02,2027-03-18,31.77,115.84,98.71,1.425603
233,SLDP,2.87,2026-04-02,2027-03-18,2.50,10.37,6.51,1.250871
76,ETSY,51.10,2026-04-02,2027-03-18,49.46,160.10,133.12,1.235356
224,PAGS,10.49,2026-04-02,2027-03-18,10.16,29.03,29.83,1.193200
252,WKEY,6.39,2026-04-02,2027-03-18,6.33,21.91,13.73,1.189358

In [ ]:
buystkrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
buystkrcfg.model_path = f'/{colab_path}/models/rolling/buystocks_1213'
buystkrcfg.model.window_size = 500
buystkrcfg.model.future_days = 250
buystkrdf = run_model_nn(f'/{colab_path}/tickers/buystockstickers.csv', cfg=buystkrcfg)

In [ ]:
buystkrdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
350,SQNS,2.41,2026-04-02,2027-03-18,2.18,7.28,3.17,0.746888
7,HIMS,19.24,2026-04-02,2027-03-18,18.21,49.25,32.37,0.729556
247,BYRN,9.11,2026-04-02,2027-03-18,8.60,20.99,15.77,0.659715
31,TEAM,68.83,2026-04-02,2027-03-18,66.35,201.89,65.50,0.616253
168,TTD,22.19,2026-04-02,2027-03-18,20.73,40.50,40.57,0.529217
17,INVZ,0.66,2026-04-02,2027-03-18,0.63,1.55,0.84,0.525253
5,DOMO,2.87,2026-04-02,2027-03-18,2.77,6.67,3.56,0.509872
22,MBLY,7.39,2026-04-02,2027-03-18,6.70,18.22,7.74,0.473162
120,LZ,5.74,2026-04-02,2027-03-18,5.50,12.22,7.48,0.463415
93,CHGG,0.75,2026-04-02,2027-03-18,0.64,1.33,1.32,0.462222
34,UP,0.50,2026-04-02,2027-03-18,0.47,1.01,0.70,0.453333
156,NOW,101.82,2026-04-02,2027-03-18,99.20,226.68,115.81,0.445983
111,CNSWF,1777.48,2026-04-02,2027-03-18,1633.38,3772.25,2040.75,0.396430
166,SWKS,54.08,2026-04-02,2027-03-18,50.09,117.94,57.49,0.390039
0,SE,81.51,2026-04-02,2027-03-18,73.73,185.03,80.98,0.389359
176,ACN,198.65,2026-04-02,2027-03-18,181.23,362.51,278.97,0.380502
349,INMD,13.75,2026-04-02,2027-03-18,12.04,22.47,22.10,0.372364
19,ADBE,241.73,2026-04-02,2027-03-18,234.84,375.59,383.98,0.371241
187,GDYN,5.69,2026-04-02,2027-03-18,5.23,11.02,7.13,0.369654
75,NVO,36.49,2026-04-02,2027-03-18,33.73,57.69,56.34,0.349776

In [ ]:
stkcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
stkcfg.model_path = f'/{colab_path}/models/transformer/stock_0105'
stkdf = run_model_nn(f'/{colab_path}/tickers/stocktickers.csv', cfg=stkcfg)

In [ ]:
# stkdf[stkdf['predicted_return'] > 0].head(20)
stkdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
110,CE,64.73,2026-04-15,2026-05-13,60.29,115.98,90.05,0.371440,0.392500
21,STX,519.60,2026-04-15,2026-05-13,285.67,533.60,312.93,-0.273672,-0.350567
332,MU,456.23,2026-04-15,2026-05-13,235.16,474.11,293.77,-0.267153,-0.320226
226,COHR,308.20,2026-04-15,2026-05-13,146.41,328.19,187.45,-0.283961,-0.319248
306,BE,213.84,2026-04-15,2026-05-13,102.22,226.89,132.21,-0.280895,-0.317562
341,ENPH,32.18,2026-04-15,2026-05-13,28.98,44.37,50.31,0.280920,0.282536
207,AGX,606.43,2026-04-15,2026-05-13,432.20,640.65,341.93,-0.222345,-0.239664
47,EL,76.60,2026-04-15,2026-05-13,71.99,103.52,102.51,0.209835,0.230518
164,EL,76.60,2026-04-15,2026-05-13,71.99,103.52,102.51,0.209835,0.230518
295,KEYS,325.25,2026-04-15,2026-05-13,169.64,334.97,260.92,-0.215445,-0.223269
371,TTMI,116.60,2026-04-15,2026-05-13,69.43,124.98,81.86,-0.210206,-0.216441
56,HUBS,218.62,2026-04-15,2026-05-13,206.00,288.10,288.36,0.193029,0.210140
100,AEHR,73.22,2026-04-15,2026-05-13,42.61,79.27,54.82,-0.195575,-0.183746
71,NOK,9.99,2026-04-15,2026-05-13,7.51,10.27,7.62,-0.152486,-0.182051
32,TEAM,66.00,2026-04-15,2026-05-13,60.60,80.98,95.55,0.197626,0.179833
255,EOSE,7.08,2026-04-15,2026-05-13,4.77,7.49,5.33,-0.171846,-0.178284
326,PSIX,83.13,2026-04-15,2026-05-13,56.51,89.79,58.46,-0.178957,-0.174581
378,PARR,62.20,2026-04-15,2026-05-13,34.68,65.73,51.43,-0.186281,-0.170095
136,POWL,229.73,2026-04-15,2026-05-13,143.77,243.28,187.33,-0.166587,-0.156527
143,BWXT,238.42,2026-04-15,2026-05-13,157.93,246.36,204.52,-0.148827,-0.146209

In [ ]:
stkrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
stkrcfg.model_path = f'/{colab_path}/models/rolling/stock_0102'
stkrdf = run_model_nn(f'/{colab_path}/tickers/stocktickers.csv', cfg=stkrcfg)

In [ ]:
# stkrdf[stkrdf['predicted_return'] > 0].head(20)
stkrdf.head(20)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
100,AEHR,73.22,2026-04-15,2026-05-13,65.94,94.83,105.12,0.210462,0.195550
226,COHR,308.20,2026-04-15,2026-05-13,287.17,400.05,394.61,0.170052,0.171467
372,CRCL,105.52,2026-04-15,2026-05-13,76.04,112.26,83.83,-0.140353,-0.133532
261,LUNR,23.88,2026-04-15,2026-05-13,22.37,32.14,27.81,0.149079,0.132774
263,PRGS,29.57,2026-04-15,2026-05-13,22.46,31.85,24.15,-0.115545,-0.096598
255,EOSE,7.08,2026-04-15,2026-05-13,5.06,7.71,5.88,-0.121940,-0.095035
245,IESC,529.22,2026-04-15,2026-05-13,509.95,723.44,552.48,0.124844,0.089400
137,STRL,456.08,2026-04-15,2026-05-13,431.90,543.14,524.43,0.095912,0.086269
374,CDE,19.67,2026-04-15,2026-05-13,15.34,21.33,15.95,-0.108287,-0.085697
371,TTMI,116.60,2026-04-15,2026-05-13,106.43,159.01,128.16,0.125214,0.084741
190,U,25.26,2026-04-15,2026-05-13,20.88,26.76,21.00,-0.094220,-0.081721
338,AEVA,14.93,2026-04-15,2026-05-13,10.72,16.36,12.71,-0.111632,-0.079662
173,TTD,22.38,2026-04-15,2026-05-13,15.50,24.93,18.82,-0.117516,-0.079135
135,CLS,381.94,2026-04-15,2026-05-13,353.65,439.85,466.03,0.099239,0.078347
138,CAAP,26.33,2026-04-15,2026-05-13,25.33,31.51,28.96,0.086213,0.077177
330,ROOT,51.70,2026-04-15,2026-05-13,43.83,55.12,42.92,-0.085300,-0.067790
256,FLEX,78.43,2026-04-15,2026-05-13,68.42,105.53,87.43,0.110884,0.063645
33,VALE,17.62,2026-04-15,2026-05-13,16.81,20.28,19.61,0.072645,0.061868
380,EWY,144.92,2026-04-15,2026-05-13,118.77,154.02,127.89,-0.078388,-0.059609
45,RMBS,120.02,2026-04-15,2026-05-13,113.81,134.06,137.84,0.071238,0.057731

In [ ]:
glbcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
glbcfg.model_path = f'/{colab_path}/models/transformer/global_0105'
glbdf = run_model_nn(f'/{colab_path}/tickers/globaltickers.csv', cfg=glbcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/global_0105_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/global_0105_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/global_0105_close_model.pth'}

In [ ]:
glbdf[glbdf['predicted_return']>0].head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
47,SE,89.17,2026-03-09,2026-04-06,85.02,102.54,122.71,0.159844
42,PROSF,51.05,2026-03-06,2026-04-03,47.33,67.48,56.32,0.117401
11,DNNGY,7.28,2026-03-09,2026-04-06,6.79,9.04,8.22,0.101190
41,POAHF,37.50,2026-03-09,2026-04-06,37.20,42.78,42.16,0.085689
61,SIFY,13.74,2026-03-09,2026-04-06,12.67,15.38,16.53,0.081514
59,ALAR,7.26,2026-03-09,2026-04-06,6.58,9.01,7.88,0.077594
6,COTY,2.28,2026-03-09,2026-04-06,2.22,2.61,2.49,0.070175
20,FQVLF,23.30,2026-03-09,2026-04-06,21.14,28.56,24.79,0.065665
51,TGLS,41.50,2026-03-09,2026-04-06,38.53,49.05,44.93,0.064337
1,ADDDF,165.00,2026-03-06,2026-04-03,161.46,188.57,174.85,0.060364

In [ ]:
glbrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
glbrcfg.model_path = f'/{colab_path}/models/rolling/global_1210'
glbrdf = run_model_nn(f'/{colab_path}/tickers/globaltickers.csv', cfg=glbrcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/global_1210_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/global_1210_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/global_1210_close_model.pth'}

In [ ]:
glbrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
61,SIFY,13.74,2026-03-09,2026-04-06,13.15,16.11,16.59,0.112324
52,TKAMY,10.70,2026-03-06,2026-04-03,10.36,12.69,12.34,0.102492
42,PROSF,51.05,2026-03-06,2026-04-03,48.54,57.40,60.82,0.088867
64,FCX,59.28,2026-03-09,2026-04-06,57.07,68.38,67.64,0.085751
65,KEP,16.13,2026-03-09,2026-04-06,15.32,19.53,17.67,0.085348
20,FQVLF,23.30,2026-03-09,2026-04-06,22.05,26.74,26.87,0.082403
37,NXPI,200.84,2026-03-09,2026-04-06,199.74,233.32,217.48,0.079699
17,ESEA,64.50,2026-03-09,2026-04-06,60.46,74.49,73.44,0.076951
9,CX,10.73,2026-03-09,2026-04-06,10.19,12.77,11.68,0.076111
39,OTGLY,16.50,2026-03-06,2026-04-03,16.03,18.79,17.96,0.066263

In [ ]:
ctcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
ctcfg.model_path = f'/{colab_path}/models/transformer/country_1211'
ctdf = run_model_nn(f'/{colab_path}/tickers/countrytickers.csv', cfg=ctcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/country_1211_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/country_1211_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/country_1211_close_model.pth'}

In [ ]:
ctdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
16,IDX,13.94,2026-04-08,2026-05-06,13.98,15.54,15.49,0.076279
7,EWI,56.62,2026-04-08,2026-05-06,48.92,56.93,55.32,-0.051160
4,EPHE,25.71,2026-04-08,2026-05-06,24.81,28.84,26.58,0.040192
8,EWJ,89.41,2026-04-08,2026-05-06,80.42,89.88,87.66,-0.038288
5,EWA,29.52,2026-04-08,2026-05-06,27.35,29.65,28.39,-0.035795
11,EWP,57.36,2026-04-08,2026-05-06,51.87,58.21,55.99,-0.034926
24,XCEM,43.96,2026-04-08,2026-05-06,40.17,44.90,42.25,-0.034577
9,EWC,56.64,2026-04-08,2026-05-06,52.10,57.21,54.84,-0.033957
12,EWT,76.36,2026-04-08,2026-05-06,69.82,77.17,74.35,-0.033787
2,FLN,26.63,2026-04-08,2026-05-06,24.51,26.84,25.88,-0.033296

In [ ]:
ctycfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
ctycfg.model_path = f'/{colab_path}/models/transformer/country_0303'
ctycfg.model.window_size = 500
ctycfg.model.future_days = 250
ctydf = run_model_nn(f'/{colab_path}/tickers/countrytickers.csv', cfg=ctycfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/country_0303_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/country_0303_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/country_0303_close_model.pth'}

In [ ]:
ctydf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
19,KEMQ,23.42,2026-03-03,2027-02-16,20.89,31.46,29.76,0.168659
18,INDA,50.25,2026-03-03,2027-02-16,49.39,62.75,63.98,0.168292
12,EWT,71.72,2026-03-03,2027-02-16,52.00,73.36,59.22,-0.142127
10,EWM,28.43,2026-03-03,2027-02-16,19.90,28.34,25.31,-0.137648
14,EWY,134.43,2026-03-03,2027-02-16,86.88,136.88,124.36,-0.136800
5,EWA,29.19,2026-03-03,2027-02-16,22.75,30.97,23.31,-0.120361
8,EWJ,87.00,2026-03-03,2027-02-16,66.87,89.01,74.22,-0.118391
3,ECH,39.46,2026-03-03,2027-02-16,28.12,39.76,36.91,-0.114800
24,XCEM,42.62,2026-03-03,2027-02-16,31.83,43.48,38.49,-0.109964
2,FLN,25.02,2026-03-03,2027-02-16,18.75,25.38,22.96,-0.106182

In [ ]:
crcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
crcfg.model_path = f'/{colab_path}/models/rolling/country_0310'
crdf = run_model_nn(f'/{colab_path}/tickers/countrytickers.csv', cfg=crcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/country_0310_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/country_0310_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/country_0310_close_model.pth'}

In [ ]:
crdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
10,EWM,28.86,2026-04-08,2026-05-06,28.03,30.64,30.75,0.032802
15,EWZ,39.57,2026-04-08,2026-05-06,37.32,40.17,38.36,-0.024092
4,EPHE,25.71,2026-04-08,2026-05-06,24.56,26.34,24.59,-0.021263
13,EWW,79.11,2026-04-08,2026-05-06,74.44,80.55,77.49,-0.020436
2,FLN,26.63,2026-04-08,2026-05-06,25.46,27.05,25.90,-0.018525
23,VNM,18.42,2026-04-08,2026-05-06,17.89,19.36,19.03,0.018458
8,EWJ,89.41,2026-04-08,2026-05-06,84.34,91.10,88.80,-0.014875
18,INDA,49.27,2026-04-08,2026-05-06,46.45,51.50,51.88,0.013666
11,EWP,57.36,2026-04-08,2026-05-06,54.38,58.57,56.81,-0.013482
17,ILF,36.79,2026-04-08,2026-05-06,34.93,37.62,36.37,-0.013138

In [ ]:
valtcfg = Config.from_file('./stock_prediction/configs/experiment.yaml')
valtcfg.model_path = f'/{colab_path}/models/transformer/valuestock_1018'
valtdf = run_model_nn(f'valuestocktickers.csv', cfg=valtcfg)

In [ ]:
valtdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
71,POWL,355.91,2025-11-12,2025-12-10,318.63,406.16,497.69,0.144934
16,CC,12.51,2025-11-12,2025-12-10,11.58,15.90,14.90,0.129230
7,ARE,53.86,2025-11-12,2025-12-10,52.99,59.89,66.73,0.111586
91,UAL,99.94,2025-11-12,2025-12-10,91.43,119.48,121.23,0.107798
14,BXC,57.66,2025-11-12,2025-12-10,55.51,69.67,63.39,0.090126
44,GLW,88.71,2025-11-12,2025-12-10,86.23,108.45,94.80,0.087739
74,RH,160.72,2025-11-12,2025-12-10,156.87,193.12,172.52,0.083686
37,F,13.45,2025-11-12,2025-12-10,12.72,13.75,10.53,-0.083024
58,MOD,147.99,2025-11-12,2025-12-10,142.12,179.25,154.26,0.071311
39,FICO,1778.19,2025-11-12,2025-12-10,1648.44,2256.72,1784.05,0.066480

In [ ]:
valrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
valrcfg.model_path = f'/{colab_path}/models/rolling/valuestock_0106'
valrdf = run_model_nn(f'/{colab_path}/tickers/valuestocktickers.csv', cfg=valrcfg)

In [ ]:
valrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
10,ASC,15.46,2026-04-08,2026-05-06,14.70,18.38,19.82,0.140578
86,NUTX,105.04,2026-04-08,2026-05-06,101.43,125.68,124.92,0.117130
66,IP,37.07,2026-04-08,2026-05-06,27.20,38.18,35.51,-0.092797
26,CF,126.16,2026-04-08,2026-05-06,118.56,159.22,133.49,0.086636
80,MP,54.44,2026-04-08,2026-05-06,51.43,62.54,63.11,0.084252
24,CCJ,115.90,2026-04-08,2026-05-06,108.59,131.75,133.98,0.076560
19,BXC,53.77,2026-04-08,2026-05-06,45.77,60.21,43.82,-0.071353
122,TWI,8.28,2026-04-08,2026-05-06,6.10,8.81,8.21,-0.069243
6,ANF,101.97,2026-04-08,2026-05-06,89.92,104.15,93.27,-0.060704
0,AAL,11.41,2026-04-08,2026-05-06,9.67,12.01,10.53,-0.059013

In [ ]:
commtcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
commtcfg.model_path = f'/{colab_path}/models/transformer/commodity_0109'
commtdf = run_model_nn(f'/{colab_path}/tickers/commoditytickers.csv', cfg=commtcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/commodity_0109_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/commodity_0109_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/commodity_0109_close_model.pth'}

In [ ]:
commtdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
5,GLD,434.53,2026-04-08,2026-05-06,352.30,432.66,422.14,-0.074019
8,SLV,67.47,2026-04-08,2026-05-06,59.86,66.41,62.03,-0.069710
0,DBC,28.56,2026-04-08,2026-05-06,25.85,28.98,27.95,-0.033847
2,FXE,107.69,2026-04-08,2026-05-06,104.99,108.25,101.93,-0.024453
7,PALL,142.43,2026-04-08,2026-05-06,131.41,152.85,138.02,-0.011725
9,SOYB,24.36,2026-04-08,2026-05-06,23.76,24.75,23.94,-0.008621
12,USO,124.58,2026-04-08,2026-05-06,122.05,135.94,112.76,-0.008000
1,FXB,128.91,2026-04-08,2026-05-06,126.77,129.72,128.40,-0.004758
13,UUP,27.53,2026-04-08,2026-05-06,27.38,27.95,27.64,0.004601
3,FXF,111.61,2026-04-08,2026-05-06,110.45,112.29,110.66,-0.004271

In [ ]:
commtbcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
commtbcfg.model_path = f'/{colab_path}/models/transformer_base/commodity_0410'
commtbdf = run_model_nn(f'/{colab_path}/tickers/commoditytickers.csv', cfg=commtbcfg)
commtbdf.head(10)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer_base/commodity_0410_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer_base/commodity_0410_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer_base/commodity_0410_close_model.pth'}

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
4,FXY,57.70,2026-04-09,2026-05-07,57.55,60.19,62.51,0.041306,1.176190
13,UUP,27.48,2026-04-09,2026-05-07,27.48,27.88,27.53,0.005459,0.842927
0,DBC,28.71,2026-04-09,2026-05-07,28.06,29.95,30.61,0.028910,0.768058
12,USO,126.96,2026-04-09,2026-05-07,122.10,133.35,140.58,0.039776,0.664151
10,TIP,110.96,2026-04-09,2026-05-07,109.62,111.74,109.64,-0.005648,-0.630008
15,WEAT,22.01,2026-04-09,2026-05-07,21.99,23.53,21.84,0.020142,0.580449
6,ISHG,75.36,2026-04-09,2026-05-07,74.37,76.34,73.34,-0.008979,-0.543672
14,VTIP,50.03,2026-04-09,2026-05-07,49.79,50.50,50.27,0.003131,0.529664
7,PALL,141.65,2026-04-09,2026-05-07,138.39,147.07,129.84,-0.022709,-0.457291
3,FXF,111.65,2026-04-09,2026-05-07,107.79,112.68,111.93,-0.007613,-0.395293

In [ ]:
commrcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
commrcfg.model_path = f'/{colab_path}/models/rolling/commodity_0312'
commrdf = run_model_nn(f'/{colab_path}/tickers/commoditytickers.csv', cfg=commrcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/commodity_0312_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/commodity_0312_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/commodity_0312_close_model.pth'}

In [ ]:
commrdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
7,PALL,142.43,2026-04-08,2026-05-06,131.20,146.14,141.30,-0.020244
11,TLT,86.92,2026-04-08,2026-05-06,84.33,87.82,83.92,-0.017986
15,WEAT,22.25,2026-04-08,2026-05-06,21.13,23.15,21.56,-0.013633
9,SOYB,24.36,2026-04-08,2026-05-06,24.03,25.28,24.47,0.009579
4,FXY,57.90,2026-04-08,2026-05-06,57.38,58.49,59.40,0.009039
12,USO,124.58,2026-04-08,2026-05-06,117.46,133.18,126.43,0.008910
8,SLV,67.47,2026-04-08,2026-05-06,62.20,70.51,68.25,-0.007164
5,GLD,434.53,2026-04-08,2026-05-06,411.25,450.66,434.61,-0.005423
14,VTIP,50.00,2026-04-08,2026-05-06,49.88,50.49,50.43,0.005333
1,FXB,128.91,2026-04-08,2026-05-06,127.55,129.70,127.59,-0.004887

In [ ]:
cryptcfg = Config.from_file('./stock_prediction/configs/transformer_base.yaml')
cryptcfg.model_path = f'/{colab_path}/models/transformer_base/crypto_0415'
cryptdf = run_model_nn(f'/{colab_path}/tickers/cryptotickers.csv', cfg=cryptcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer_base/crypto_0415_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer_base/crypto_0415_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer_base/crypto_0415_close_model.pth'}

In [ ]:
cryptdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return,conviction
17,MATIC-USD,0.22,2025-03-24,2025-04-21,0.15,0.23,0.16,-0.181818,-0.204346
13,LINK-USD,9.07,2026-04-15,2026-05-13,8.78,11.34,11.73,0.170526,0.201573
10,BCH-USD,435.47,2026-04-15,2026-05-13,430.44,676.57,461.04,0.200274,0.159470
6,DOGE-USD,0.09,2026-04-15,2026-05-13,0.09,0.10,0.10,0.074074,0.104757
1,ETH-USD,2331.67,2026-04-15,2026-05-13,1846.80,2454.00,2032.68,-0.094572,-0.082095
11,ICP-USD,2.42,2026-04-15,2026-05-13,2.20,2.85,2.88,0.092287,0.065697
4,XRP-USD,1.36,2026-04-15,2026-05-13,1.25,1.57,1.49,0.056373,0.031785
8,LTC-USD,54.16,2026-04-15,2026-05-13,53.59,63.47,53.37,0.048929,0.027528
3,ADA-USD,0.24,2026-04-15,2026-05-13,0.23,0.29,0.23,0.041667,0.014731
5,DOT-USD,1.17,2026-04-15,2026-05-13,1.12,1.49,1.03,0.037037,0.008063

In [ ]:
cryprcfg = Config.from_file('./stock_prediction/configs/rolling.yaml')
cryprcfg.model_path = f'/{colab_path}/models/rolling/crypto_0109'
cryprdf = run_model_nn(f'/{colab_path}/tickers/cryptotickers.csv', cfg=cryprcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/rolling/crypto_0109_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/rolling/crypto_0109_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/rolling/crypto_0109_close_model.pth'}

In [ ]:
cryprdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
6,DOGE-USD,0.09,2026-02-23,2026-03-23,0.09,0.11,0.10,0.111111
1,ETH-USD,1886.96,2026-02-23,2026-03-23,1330.20,2174.07,1709.21,-0.079034
18,ATOM-USD,2.14,2026-02-23,2026-03-23,2.02,2.54,2.33,0.073209
2,SOL-USD,78.93,2026-02-23,2026-03-23,59.76,87.89,72.00,-0.072385
0,BTC-USD,65295.14,2026-02-23,2026-03-23,59270.92,81705.72,67312.41,0.063321
17,MATIC-USD,0.22,2025-03-24,2025-04-21,0.19,0.24,0.19,-0.060606
4,XRP-USD,1.37,2026-02-23,2026-03-23,1.08,1.60,1.24,-0.046229
11,ICP-USD,2.05,2026-02-23,2026-03-23,1.90,2.29,1.72,-0.039024
16,AAVE-USD,116.05,2026-02-23,2026-03-23,101.88,128.02,106.10,-0.034899
13,LINK-USD,8.41,2026-02-23,2026-03-23,7.21,10.21,8.39,0.022989

In [ ]:
etftcfg = Config.from_file('./stock_prediction/configs/transformer.yaml')
etftcfg.model_path = f'/{colab_path}/models/transformer/etf_0112'
etftdf = run_model_nn(f'/{colab_path}/tickers/etftickers.csv', cfg=etftcfg)

Loading models for return types: {'min': '/content/drive/MyDrive/colab/models/transformer/etf_0112_min_model.pth', 'max': '/content/drive/MyDrive/colab/models/transformer/etf_0112_max_model.pth', 'close': '/content/drive/MyDrive/colab/models/transformer/etf_0112_close_model.pth'}

In [ ]:
etftdf.head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
4,DXYZ,24.36,2026-03-20,2026-04-17,23.76,32.65,28.18,0.157499
9,IPOS,17.97,2026-03-20,2026-04-17,17.84,18.88,20.56,0.062512
19,SMH,384.74,2026-03-20,2026-04-17,355.84,399.67,327.85,-0.061392
14,IWO,309.55,2026-03-20,2026-04-17,280.17,321.37,281.84,-0.048748
30,XLK,135.29,2026-03-20,2026-04-17,123.68,141.20,121.64,-0.047675
23,VIS,311.14,2026-03-20,2026-04-17,309.53,335.62,332.47,0.047353
1,ARKK,69.15,2026-03-20,2026-04-17,68.60,76.81,71.43,0.045264
25,XLB,46.98,2026-03-20,2026-04-17,46.12,50.78,50.24,0.043990
35,XME,101.73,2026-03-20,2026-04-17,98.10,108.56,111.24,0.041646
11,IXN,101.08,2026-03-20,2026-04-17,89.26,106.09,95.90,-0.039540

In [ ]:
from google.colab import auth
import gspread
from oauth2client.client import GoogleCredentials
import pandas as pd
from google.auth import default


auth.authenticate_user()


creds, _ = default()
gc = gspread.authorize(creds)
# gc = gspread.authorize(GoogleCredentials.get_application_default())

In [ ]:
# Open your spreadsheet by name
spreadsheet = gc.open('Allocation')
# Or by URL: spreadsheet = gc.open_by_url('Your Spreadsheet URL')

# Select the worksheet (e.g., the first sheet)
worksheet = spreadsheet.worksheet("Buy")

# Get all values as a list of lists
data = worksheet.get_all_values()

# Convert to a Pandas DataFrame
sheetdf = pd.DataFrame(data[1:], columns=data[0]) # Assuming first row is header

In [ ]:
df = sheetdf[['Ticker']].copy()

# Apply the extraction function first, then filter based on the result
def extract_ticker(ticker_str):
    # Convert to string before splitting
    ticker_str = str(ticker_str)
    parts = ticker_str.split(':')
    if len(parts) > 1:
        return parts[1].strip() # Use strip to remove leading/trailing whitespace
    return ticker_str.strip() # Return the original string if no colon, also strip whitespace

df['Ticker'] = df['Ticker'].apply(extract_ticker)
# Remove BTCUSD and add BTC-USD, ETH-USD, ADA-USD, SOL-USD in Ticker
df = df[df['Ticker'] != 'BTCUSD']
df = pd.concat([df, pd.DataFrame({'Ticker': ['BTC-USD', 'ETH-USD', 'ADA-USD', 'SOL-USD']})], ignore_index=True)
df.to_csv(f'/{colab_path}/tickers/stocktickers.csv', index=False)
df.to_csv(f'/{colab_path}/tickers/buystockstickers.csv', index=False)

In [ ]:
# Only have Tickers column

run_model_nn('buystocks', '0402', False, 500, 250, copy_tickers=False).head(10)

,ticker,current_price,current_date,prediction_date,predicted_min,predicted_max,predicted_close,predicted_return
333,QBTS,34.25,2025-10-08,2026-09-23,32.44,71.01,65.57,0.644964
96,CHGG,1.42,2025-10-08,2026-09-23,1.40,2.82,2.74,0.633803
97,SLP,16.47,2025-10-08,2026-09-23,16.09,32.07,31.69,0.616070
18,OUST,30.65,2025-10-08,2026-09-23,29.45,61.59,56.80,0.607830
9,HIMS,58.17,2025-10-08,2026-09-23,49.10,110.63,110.40,0.547934
252,LYFT,21.16,2025-10-08,2026-09-23,19.66,41.40,36.93,0.543636
6,DOMO,14.74,2025-10-08,2026-09-23,12.98,29.59,25.17,0.531886
326,ROOT,81.73,2025-10-08,2026-09-23,76.40,156.09,141.76,0.526367
122,LZ,9.97,2025-10-08,2026-09-23,9.63,19.32,16.65,0.524574
276,CRNC,11.96,2025-10-08,2026-09-23,11.62,21.43,21.43,0.518395

In [ ]:
 # !cp -ru results /content/drive/MyDrive/colab
 !rsync -av --ignore-existing results/* /content/drive/MyDrive/colab/results/
 ! find /content/drive/MyDrive/colab/ -type f -mtime +180 -delete -print

sending incremental file list
buystocks_0709_predictions.csv

sent 18,897 bytes  received 35 bytes  37,864.00 bytes/sec
total size is 18,770  speedup is 0.99

In [ ]:

# update zip /tmp/stock_cache.zip from files in folder /tmp/stock_cache
!zip -r /tmp/stock_cache.zip /tmp/stock_cache
!cp /tmp/stock_cache.zip /content/drive/MyDrive/colab/

In [ ]:
# Copy zip file from /content/drive/MyDrive/colab/ to /tmp/stock_cache.zip
!cp /content/drive/MyDrive/colab/stock_cache.zip /tmp/stock_cache.zip
!unzip  /tmp/stock_cache.zip